### ISSUE TITLE
Make possible to attach picker to dom without linking it to a form field

### ISSUE THREAD

**Issue by mwoc** [dbushell/Pikaday#105]
In some cases, it might be nice to just have a span containing the date in a certain format, with a button next to it to change the value, so without an input field. 

However I can't seem to get pikaday to work with just a trigger and no field parameter - pikaday doesn't attach the date picker to the dom when no field is supplied in the config.

What might solve this, is adding an extra config param specifying to which DOM element the date picker should be linked, defaulting to the element supplied as 'field'. 

This would also solve https://github.com/dbushell/Pikaday/issues/88 and make solving https://github.com/dbushell/Pikaday/issues/48 easier.

**Comment by tamirvs** [comment]
@rikkert The container option doesn't work unless you also set a field. You have to add the picker using @dmarkow's solution.
