### ISSUE TITLE
formatting date

### ISSUE THREAD

**Issue by madvik** [dbushell/Pikaday#120]
Hello,
Pickaday is a good tool but, I test to format the date in the input and it's doesn't work.
I find the solution int the closed issue. ->" You need to load the libraries in the good order : moment.js before pickaday.js"
But it's complicated just for a format while the Date format is a good solution, furthermore this is a dependency to Moment.js.
Is it possible to embed the default format of the class Date?

**Comment by goranefbl** [comment]
Pretty old, but i just replaced toString format ,line 671 with:

        toString: function(format)
        {
            return this._d.getDate()  + "-" + (this._d.getMonth()+1) + "-" + this._d.getFullYear();
        },

which gives me what i wanted without using one more script.
