### ISSUE TITLE
Date does not select on mobile (iOS)

### ISSUE THREAD

**Issue by zerostyle** [dbushell/Pikaday#121]
I tried to select a date on my iPad, but the date does not get selected. The tap event seems to work, but the date does not change when a new date has been chosen.

**Comment by jamespacileo** [comment]
Having same issue on iOS8. I've only tested on iPhone 6 devices within Safari.

**Comment by wmonk** [comment]
@rikkert this issue still stands. The example that you refer to does not use the same version of Pikaday.js as the production one in the repo.

The difference that is causing this error is:

production:
```
addEvent(self.el, 'ontouchend' in document ? 'ontouchend' : 'mousedown', self._onMouseDown, true);
```

demo:
```
addEvent(self.el, 'mousedown', self._onMouseDown, true);
```
