### ISSUE TITLE
Calendar display "disappears" quickly using small trigger buttons

### ISSUE THREAD

**Issue by dslack** [dbushell/Pikaday#125]
Experienced this today.  I'm using Bootstrap, and have a button field with the calendar icon.  When I bind the calendars trigger to that button, I have some really strange behaviour where clicking on the button will open and close the calendar immediately (but, only sometimes).

Here is a jsbin showing the issue (happens on Chrome):

http://jsbin.com/tiwayufo

**Comment by robertfall** [comment]
Did you make any progress with this? I'm experiencing the same thing and it causes the month and year select to be unusable. 

I don't have any custom buttons, simply changing years doesn't match with the trigger element and thus causes the calendar to be hidden.

**Comment by robertfall** [comment]
After digging in further and creating a fix to submit I did a final search and found that this has been fixed already by this commit:  https://github.com/dbushell/Pikaday/commit/e6d3eadadeb31c8ba5f6a924b60e6c2f5e4a90ce

The code was released in 1.3.2 and I reckon this issue can be closed.
