### ISSUE TITLE
Add an onChange event listener...

### ISSUE THREAD

**Issue by markstickley** [dbushell/Pikaday#126]
...to differentiate between when the date changes because the user selected it and when it changes because of some script telling it to.

Currently when you call setDate, the onSelect callback gets triggered, but no date was physically selected. It would be nice to be able to change the date without the callback running (as my callback loads a new page and should only be run when a user clicks).

Thanks!

**Comment by denvaar** [comment]
I am using GET parameters to submit a form when a date is selected. Calling ```submit();``` from the onChange event is causing the page to loop infinitely. Is there a way around this ?
