### ISSUE TITLE
Issue when parsing a date in western timezones

### ISSUE THREAD

**Issue by regebro** [dbushell/Pikaday#138]
We have date inputs that look like this, which we use Pikaday 1.2.0 with:

<input type="date" value="2014-04-17" placeholder="Date" name="startDate-day" class="date pat-date-picker focus" size="10">

I've noticed that Pikaday will parse the date 2014-04-17 and convert it into a JS Date object. But if you have a timezone that is west of UTC, it will intepret it as 2014-04-17 00:00, UTC, and promptly fill in the field with "Wed Apr 16 2014". Saving the form will submit 2014-04-16 and the date will change.

This has been replicated on IE10 and FF28.

One solution could be to change the line

```date = new Date(Date.parse(opts.field.value))```

to 

```date = new Date(Date.parse(opts.field.value) + 43200000)```

To add 12 hours to the date. But it is a bit hackish, and there *are* UTC-13 timezones out there where it still would not work. 

(We do use moment.js as well, but for some reason Pikaday doesn't seem to detect it).

**Comment by derduher** [comment]
@regebro et al after struggling with this problem myself for several hours it dawned on me that YYYY-MM-DD is in fact ISO-8601. While ISO-8601 specifies that [strings without zone specifiers are to be treated as local time](http://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) Date.parse in javascript [deviates from this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#ECMAScript_5_ISO-8601_format_support) in ES5 and assumes UTC. ES6 is expected to correct this. In the mean time you can use setMoment to obtain the correct behavior.

Note however setMoment has inconsistencies with Date.parse. eg '' is not parsed as Invalid Date. I might open a tick for that.

**Comment by jkrasnay** [comment]
An easy workaround is to construct the date using integer fields, e.g. new Date(2015, 5, 16). Note that the month must be zero-based.
