### ISSUE TITLE
Position incorrect when inside a scrollable element

### ISSUE THREAD

**Issue by TRPB** [dbushell/Pikaday#194]
If I create an element with 

``` css
overflow: auto; position:relative; 
```

The absolutely positioned pikaday window should display under the input. However, the value for top given to the div.pika-single is not calculated correctly, it does not account for the parent element's scrollTop.

It would actually be better to place the Pikaday element directly below the target input in the HTML and assign it position:absolute rather than inside the body tag, this would remove the need for a lot of the positioning logic.

**Comment by vidit1** [comment]
@TomBZombie I am stuck with this issue.How to place the Pikaday element directly below the target input

**Comment by TomBZombie** [comment]
I updated to the latest version at the time (back in october 2014) and it fixed it for me, I didn't need to do anything else.
