### ISSUE TITLE
Incompatible with almond

### ISSUE THREAD

**Issue by egucciar** [dbushell/Pikaday#196]
Pikaday with moment.js is incompatible with almond. Please state this explicitly in the documentation, and offer a pikaday js file which defines moment as a dependency which will work with almond.

**Comment by dbashford** [comment]
:+1:

**Comment by dbashford** [comment]
One update to the description above.

This is not entirely true.
> and even if it did it would not work since almond cannot use require() call to load files asyncrounously. This is because what ends up becoming built in the program will not contain moment as it is not listed explictly as a depenency in the define block.

It doesn't matter that moment isn't mentioned in the define block.  What is passed into moment is the `require` function, which provides access to any previously defined modules by id.  If you have defined something as `"moment"`, and then shimmed pikaday with "moment" as a dependency, then this will work:

```
var id = 'moment';
moment = req(id)
return factory(moment);
```

I'm not sure what the right solution here is, but I don't see the harm in changing this line

```
moment = req.defined && req.defined(id) ? req(id) : undefined;
```

To this:
```
try { moment = req(id) } catch (e) {}
```

Almond doesn't have the same mechanisms to discover defined modules.  It does, as of a recent version, expose a `_defined` object (not a function), but its meant for tooling/debugging purposes.  Not sure if it is appropriate for use here.

**Comment by egucciar** [comment]
@dbashford yes you are right. Thanks for pointing that out. 3 months ago I misunderstood requirejs dependency discovery. Fortunately since then I figured out more about requirejs and realized it actually does load dependencies just fine even if they are "required". 

Regardless the issue still remains with the require.define method being undefined. This means moment never actually gets required...So your suggestion seems like a good alternative solution to the issue.

Thanks again for pointing out the issue with my original post.

**Comment by dbashford** [comment]
Thanks for the fix!
