### ISSUE TITLE
Printing prints "old" dates

### ISSUE THREAD

**Issue by mstang** [dbushell/Pikaday#211]
I have a Pikaday embedded in my page.  After changing the date multiple times and printing the page I get "calendars" embedded in my page.  I get one for each time I change the date.

It looks something like:

April April
2014 2014
Previous Month Next Month
Sun (Sunday)Mon (Monday)Tue (Tuesday)Wed (Wednesday)Thu (Thursday)Fri (Friday)Sat (Saturday)
1 2 3 4 5
6 7 8 9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30

These "calendars" are not visible except when I print.  Also, here they are text, in the printed (window.print) version, they are graphical.

Any thoughts on how to not make them appear?  And also, I am concerned that over a days use the number of these will be embedded in my DOM.

Thanks!

Mark

**Comment by fernandofleury** [comment]
This is a strange behavior. Because when i inspect the calendar there is only the current month rendered.

I will try to reproduce this behavior while printing.

**Comment by fernandofleury** [comment]
http://dbushell.github.io/Pikaday/

Can you reproduce the behavior on the demo page?

**Comment by mstang** [comment]
Couldn't, maybe I am creating more than one or a new one every time I pick
a date...

Thanks!

**Comment by fernandofleury** [comment]
If you want, you can put up a plunker with the code and the can look for the source of it.

**Comment by mstang** [comment]
Thanks, it might be related to my Om project...
