### ISSUE TITLE
how to change Default format Tue Dec 09 2014 to DD/MM/YEAR in textbox 

### ISSUE THREAD

**Issue by Maheshkani** [dbushell/Pikaday#215]
Hi ,

With Pikaday if I pick a date from the calendar it is showing Day date Mon year Format .I need Something  like DD/MM/YEAR ie 09/12/2014.

Please let me know the what are all the changes that i need to do.

Thank you 
Mahesh

**Comment by fernandofleury** [comment]
Sorry for the late response, was taking a break. :)

Ah, basically what you want to do is include moment before pikaday, and then when you create a new instance of Pikaday and include the custom format you want:

https://gist.github.com/fernandofleury/0c54f68dd76b255f9e56

**Comment by j3tchy** [comment]
Using format: 'DD/MM/YYYY' seems to bring up problems. 
I have created a JSBin to demonstrate: http://jsbin.com/bumaxi/2/ 

If I select 15th May 2015, the textfield shows 05/03/2016.

**Comment by rikkert** [comment]
Can't reproduce.

**Comment by j3tchy** [comment]
Just to confirm, you're unable to see the 'too much recursion' error within the console when using the example in the jsbin?

**Comment by rikkert** [comment]
The example jsbin works correctly for me when selecting the day you mentioned.

**Comment by j3tchy** [comment]
I've typed it out again to make sure I'm not going crazy and produced this jsbin: http://jsbin.com/nuxasipedi/1/edit

If you select 2nd March, you should see 02/03/2015. Select the box again and the calendar assumes that 3rd Feb has been selected. Once you have selected a value, instead of understanding the value as DD/MM/YYYY, it understands it as MM/DD/YYYY

**Comment by j3tchy** [comment]
So the problem was the way I was setting the date within Ember. I was setting the value and then running another function which was putting the application in an infinite loop. This can be closed now. Sorry for the inconvenience.

**Comment by pescweb** [comment]
Hello! I am working on a site in joomla and I saw that your code is in the module s5_quick_contacte I can not change the date to pt-br (English-Brazil) with this format: DD-MM-YYYY to stay like this 10-10-2017. I would be very grateful if you would help me in this situation. Thank you A hug Miro Baía

**Comment by pescweb** [comment]
Hello! I am working on a site in joomla and I saw that your code is in the module s5_quick_contacte I can not change the date to pt-br (English-Brazil) with this format: DD-MM-YYYY to stay like this 10-10-2017. I would be very grateful if you would help me in this situation. Thank you A hug Miro Baía

**Comment by azhararmar** [comment]
> > Sorry for the late response, was taking a break. :)
> > Ah, basically what you want to do is include moment before pikaday, and then when you create a new instance of Pikaday and include the custom format you want. Pikaday will simply understand you've got moment included and will let moment handle it:
> > ```
> > <script src="moment.js"></script>
> > <script src="pikaday.js"></script>
> > <script>
> >  var picker = new Pikaday({
> >   // just showing the format option
> >   format: 'DD/MM/YYYY'
> >  });
> > </script>
> > ```
> > And for the formatting options: http://momentjs.com/docs/#/displaying/
> 
> Its working fine

This is missing piece in the documentation, if you do not include moment js before including pikaday format parameter does not work.

**Comment by BernhardSigl** [comment]
> > > Sorry for the late response, was taking a break. :)
> > > Ah, basically what you want to do is include moment before pikaday, and then when you create a new instance of Pikaday and include the custom format you want. Pikaday will simply understand you've got moment included and will let moment handle it:
> > > ```
> > > <script src="moment.js"></script>
> > > <script src="pikaday.js"></script>
> > > <script>
> > >  var picker = new Pikaday({
> > >   // just showing the format option
> > >   format: 'DD/MM/YYYY'
> > >  });
> > > </script>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And for the formatting options: http://momentjs.com/docs/#/displaying/
> > 
> > 
> > Its working fine
> 
> This is missing piece in the documentation, if you do not include moment js before including pikaday format parameter does not work.

this worked for me as well. thank you
