### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by SimpleIX** [dbushell/Pikaday#219]
Hola, we are trying to do a date range picker for search - we have a checkbox that enables the option to filter by date, however if the user selects a date range, and afterwards unchecks(disables) the filter from search results, we get the uncaught rangeError exception.

Our code sample:

``` javascript
  $("#dateCheck").click(function () {
    var picker = new Pikaday({
      field: document.getElementById('startDate'),
      format: 'MM/DD/YYYY',
    });
    var picker = new Pikaday({
      field: document.getElementById('endDate'),
      format: 'MM/DD/YYYY',
      onSelect: validateEndDate
    });
    $(".date-fields").toggleClass("enabled");
    $(".date-fields input").prop('disabled', !$(this).is(':checked'));
  )};
```

``` html
<div class="date-fields">
<input type="text" value="" id="startDate" placeholder="MM/DD/YYYY" maxlength="10" disabled>
<input type="text" id="endDate" value="" class="datefield" placeholder="MM/DD/YYYY" disabled>
</div>
```

**Comment by dogui1718** [comment]
I have the same problem but, I need create a new instance each time because I am rendering the divs reactively and, everytime that the divs is unrendered and rendered Pikaday don't apear. So, I am trying to destroy the instance when the divs is unrendered but, it doesn't work. Please, may somebody help me?

**Comment by dogui1718** [comment]
I already fix my problem! My code below:

When I open the form where Pikaday is located, I run this method:

openCompose: function (){
if( !this.news.composeForm.show ){
var picker = ''; <--- Here I declare the variable "picker" empty
this.datePicker(); <--- Here I call to the method "datePicker()";
}
}

When I close de form I call the "datePicker('destroy')";

closeCompose: function (){
this.datePicker('destroy'); <----
}

The method is below:

datePicker : function (p) {
if ( p == 'destroy' ) { <--- When I send 'destroy'
picker.destroy(); <--- The variable 'picker', wich now is an instance of Pikaday, can execute the method "destroy()";
}else { <--- if a send not parameters
picker = new Pikaday({ <---- then create a new instance of Pikaday in the variable 'picker'
field: document.getElementById('datepicker'),
minDate: new Date(),
format: 'DD/MM/YYYY'
});
}
}

I hope this help to anyone ;)

Thank you!
