### ISSUE TITLE
Update release for Bower

### ISSUE THREAD

**Issue by gazdanebojsa** [dbushell/Pikaday#221]
This is somewhat similar to #151. I would appreciate if you could bump up the version (almost a year since the latest release) as the one pulled with Bower misses some very handy features ('container' for starters). 

If this is not possible, let me know as I would rather fork than have a specific commit as a dependency.

**Comment by fernandofleury** [comment]
+1

**Comment by mtmacdonald** [comment]
+1

**Comment by rikkert** [comment]
1.3.0 is released.
