### ISSUE TITLE
Unable to select month/year via selector in the titlebar

### ISSUE THREAD

**Issue by rbtbar** [dbushell/Pikaday#224]
Hi,

Please check the following [jsfiddle demo](http://jsfiddle.net/rbtbar/m6uyLxm9/): 
just click on the month/year selector and the calendar is immediately closed.

![month-year-selection-bug](https://cloud.githubusercontent.com/assets/6705643/5503613/59941c50-8779-11e4-94da-9a1ac468d8be.png)

As far I can tell, the bug is in the _onClick function, that checks whether the clicked element is owned by the trigger: 

```javascript
if (self._v && pEl !== opts.trigger) { // UUUPSSS: neither pika-select nor its parents belong to the trigger
self.hide();
}
```
The bug is related to the changes introduced to solve the following issue: https://github.com/dbushell/Pikaday/issues/188

Best Regards,
Robert

**Comment by Freyskeyd** [comment]
i'm experiencing the same problem.
