### ISSUE TITLE
Feature request: Update callbacks via API

### ISSUE THREAD

**Issue by espen** [dbushell/Pikaday#225]
Something like:

        /**
         * set the onDraw callback
         */
        setOnDraw: function(callbackFunction)
        {
            this._o.onDraw = callbackFunction;
        }

I can make a pull request if this sounds good.

**Comment by fernandofleury** [comment]
I suppose it could have a bit more generic method, a simple updating function that expects the method and the callback for it:

```javascript
updateMethod: function(method, callback) {
 if(!self_.o[method]) {
  return false;
 }
 self_.o[method] = callback;
}
```

**Comment by rikkert** [comment]
The config should be enough.
