### ISSUE TITLE
Improve release versioning / tagging

### ISSUE THREAD

**Issue by mtmacdonald** [dbushell/Pikaday#229]
As far as I can see, the [demo page](http://dbushell.github.io/Pikaday) uses an unspecified version of pikaday that is neither the latest release (1.2.0), nor master.

It's also been nearly a year since a release was tagged, and yet master has open issues, preventing production use.

Could we have periodic, stable releases, and keep the demo page in sync with the latest release?

**Comment by rikkert** [comment]
Yes, 1.3 was released and the demo page should use the latest tag.

**Comment by rikkert** [comment]
Updated demo page.
