### ISSUE TITLE
Pressing 'tab' open calender when using 'trigger' option

### ISSUE THREAD

**Issue by andreynering** [dbushell/Pikaday#235]
Reproduce steps:

- Open this JSFiddle: http://jsfiddle.net/0Lgo5Log/2/
- Click on the first input
- Type a date like '31122012'
- Press 'tab'

The focus should go to the second input, but instead it opens the calendar. The calendar should only be opened when the user clicked the button.

**Comment by danielcrisp** [comment]
Hmm, same here - did you ever find a solution / workaround for this?

**Comment by nathancahill** [comment]
See #347

**Comment by danielcrisp** [comment]
Thanks Nathan, its not merged right?

**Comment by nathancahill** [comment]
It's not. I see your fix at b833475, would be worth submitting a PR for as well.

**Comment by tilmanpotthof** [comment]
+1
