### ISSUE TITLE
"Prev. month" and "Next month" buttons do not work on touch devices

### ISSUE THREAD

**Issue by andreynering** [dbushell/Pikaday#242]
Previous and next buttons do not work on Chrome for Android:

![pikaday](https://cloud.githubusercontent.com/assets/7011819/5840869/c54b0c18-a17f-11e4-8429-78aed304ce60.png)

It works fine on Chrome and Firefox for desktop.

JSFiddle to try: http://jsfiddle.net/0Lgo5Log/4/

**Comment by nverba** [comment]
I think this is due to rather buggy support for the text-indent property on some mobile devices.

**Comment by nverba** [comment]
Assuming the button text is just there for accessibility, perhaps you could drop the text-indent and set the button text colour to transparent?

**Comment by andreynering** [comment]
@nverba You was right about `text-indent`. Setting the text color to transparent worked too!

Thank you for helping! I made a PR.
