### ISSUE TITLE
Disabling a date range

### ISSUE THREAD

**Issue by jonnymaceachern** [dbushell/Pikaday#245]
Hi, I'd like to disable a date range depending on the users first selection.

For example, I have two calendars. One for a start date, and one for an end date. If the user selects January 22nd, then the minimum date selectable on the end date calendar is two months from that date (~March 22nd). Does pikaday have an option or method that can help with this?

**Comment by rikkert** [comment]
You need to handle this yourself in the callback:
````javascript
disableDayFn
````
