### ISSUE TITLE
I18n: Selected date not in the given I18n language

### ISSUE THREAD

**Issue by nayaabkhan** [dbushell/Pikaday#248]
I am using v1.3.1 with moment.js. The picker is invoked so:

```javascript
picker = new Pikaday({
  field: $dateInput,
  format: 'dddd DD MMMM YYYY   (DD/MM/YYYY)',
  minDate: new Date(),
  i18n: {
    previousMonth : 'Mois Précédent',
    nextMonth     : 'Mois Prochain',
    months        : 'Janvier_Février_Mars_Avril_Mai_Juin_Juillet_Août_Septembre_Octobre_Novembre_Décembre'.split('_'),
    weekdays      : 'Dimanche_Lundi_Mardi_Mercredi_Jeudi_Vendredi_Samedi'.split('_'),
    weekdaysShort : 'Dim._Lun._Mar._Mer._Jeu._Ven._Sam.'.split('_')
  },
});
```

In the Date Picker that shows up on selecting the input field, the months and days are labelled correctly in French. But when I pick a date, the input field shows the date in English as something like `Saturday 31 January 2015 (31/01/2015)`.

Is it supposed to be so? I was expecting the output date to be in French as well. What is the way to get the output date in the desired language?

**Comment by Kera** [comment]
Slt,
Maybe trying this syntax : 
```javascript
i18n: {
			previousMonth : 'Mois précédent',
			nextMonth     : 'Mois suivant',
			months        : ['Janvier','Fevrier','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Decembre'],
			weekdays      : ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
			weekdaysShort : ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam']
		}
```

**Comment by rikkert** [comment]
You have set the i18n options for Pikaday but not for Moment which is used in field output.
Set the moment i18n options and re-use them in the Pikaday options as well.

**Comment by cTahirih** [comment]
I have the same problem, but I don't use moment.js
