### ISSUE TITLE
replace onmousedown with onmouseup

### ISSUE THREAD

**Issue by forwardever** [dbushell/Pikaday#249]
is there a chance to replace onmousedown with onmouseup events?

problem: when clicking on a day in chrome browser, and holding the mouse button a bit longer than normal, while moving the mouse only slightly, the whole page gets "selected" (that means highlighted, starting from the position of the datepicker to the end of page)

also, the event should not fire when draggin the mouse outside the target's region (the day selected on mousedown)

**Comment by forwardever** [comment]
suggestion:
https://github.com/forwardever/Pikaday/commit/cf2f159b4891811ae0dab95b7ffc8d4f0b4dbdad

e.g. the datepickers of the bigger booking portals like expedia.com and booking.com have similar behaviour

**Comment by rikkert** [comment]
As soon as I click the whole popup is gone I can't drag and select anything.

**Comment by forwardever** [comment]
@rikkert 
if I get you right, you cannot reproduce the behaviour described above?

I faced the problems just on Chrome (Windows), the problem does not appear on Firefox or Internet Explorer.

**Comment by forwardever** [comment]
screenshot

![1](https://cloud.githubusercontent.com/assets/151602/5999914/899d5eda-aad7-11e4-8d02-940dd0a71ecc.gif)

**Comment by forwardever** [comment]
<html>
      <head>
        <script type="text/JavaScript" src="pikaday.js"></script>
        <link href="pikaday.css" rel="stylesheet" type="text/css" />
      </head>
      <body>
    
        <input type="text" id="datepicker">
        <div id="test">HELLO</div>
        
        <script src="pikaday.js"></script>
        <script>
            var picker = new Pikaday({ field: document.getElementById('datepicker'), trigger: document.getElementById('test') });
        </script>
        
        <div>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
        </div>
        
      </body>
    </html>

**Comment by forwardever** [comment]
another screenshot with code (datepicker in larger div)

![2](https://cloud.githubusercontent.com/assets/151602/6000050/22805dea-aad9-11e4-9285-ebadfb4a1b87.gif)


    <html>
      <head>
        <script type="text/JavaScript" src="pikaday.js"></script>
        <link href="pikaday.css" rel="stylesheet" type="text/css" />
      </head>
      <body>
    
       
        <div>
          
          <input type="text" id="datepicker">
          <div id="test">HELLO</div>
          
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
          AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA<br>
        </div>
        
        <script src="pikaday.js"></script>
        <script>
            var picker = new Pikaday({ field: document.getElementById('datepicker'), trigger: document.getElementById('test') });
        </script>
        
      </body>
    </html>

**Comment by Tom303** [comment]
I also found this to be an issue, but as a dirty fix (workaround) i just increased the time on line 490 (https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L490) from 50 to 100. This adds a slight delay between the click events and seems to keep chrome happy.

**Comment by rikkert** [comment]
To me this seems default browser behavior.
When I click and start dragging, the picker closes and then I start selecting text.
This is not strange right?

**Comment by forwardever** [comment]
@rikkert it is an annoying user experience,  as selecting text is **NOT** intended, but happens nonetheless

not sure why nobody has complained so far, seems like the issue is limited to chrome on windows, which in my case are 20%

**Comment by schoenkaft** [comment]
I can confirm the same behaviour on Chrome 40 (latest stable) and Safari 8.0.3 (latest stable) on OS X. It's very annoying and it's actually a poor user experience, and should be prevented at any point. Pikaday is a 'user-interface object', not 'content' that should be selectable. 

Here's a screenshot when selecting a date from Pikaday (PIkaday is closed after selecting a date, but all other surrounding object get select):

![screen shot 2015-02-18 at 03 53 51](https://cloud.githubusercontent.com/assets/1607628/6241744/c857fd5e-b722-11e4-943f-f156f1505ab4.png)

Of course there's custom styling and functions, but still selecting a date should prevent any other event from firing.

Using `user-select: none` on any element near and crazy `pointer-events` would be a poor solution
A simple `fix` should be to add `e.preventDefault();` to `self._onMouseDown = function(e)` in `Pikaday = function(options)`.
This should still bubble up, but prevent any 'default' browser behaviour, including the 'non-wanted' select. Any thoughts on this?

**Comment by rikkert** [comment]
Does it work? :)

**Comment by rikkert** [comment]
Had to remove the preventDefault because it breaks the month and year dropdown.
