### ISSUE TITLE
Release versions and master

### ISSUE THREAD

**Issue by ConorNugent** [dbushell/Pikaday#252]
I installed Pikaday via bower to use in an Ember project I working on. It's great but I did run into one small issue. I was a bit surprised that the disableDayFn callback I was passing into through options objects just didn't seem to be being called. I did some digging through the source code and couldn't see why there should be problem. I decided to check what version I had installed via bower and it seemed to be the most update. It was only when I downloaded v1.3.1 source code that I realised that it is quite different to the master version and seems to be based off the gh-pages branch

It's just a small thing but I was just wondering what your release process is and if it might be worth adding a note to the master README.md file to alert people to the fact that the release version is based on gh-pages branch and that they should look at the docs related to that branch

**Comment by rikkert** [comment]
Master is being developed on.
gh-pages should use the latest tag, 1.3.1 atm.
And bower also downloads the latest tag.
To see what features are included have a look at the [changelog](https://github.com/dbushell/Pikaday/blob/master/CHANGELOG.md).

**Comment by ConorNugent** [comment]
I just noticed that master seems to have been reset to the 1.3.1 version. I created a fork based on the version of the master we pulled a two days ago just so we might have somethings stable with the disableDayFn going forward but I was just  wanted to let you know just case this was done by accidenet

**Comment by rikkert** [comment]
Thanks, this was indeed a mistake.
Merged back the disableDayFn stuff and started 1.4 now.
