### ISSUE TITLE
setMinDate not working as expected

### ISSUE THREAD

**Issue by mauriciosoares** [dbushell/Pikaday#254]
Hey there!

I think there's an issue occurring in Pikaday,

When I first start the plugin, I set the configurations like this:
```js
var pikaday = new Pikaday({
  minDate: moment().add(2, 'days').toDate()
})
```

This works as expected, it allows me to pick a day 2 days from today.

But if I do this:

```js
// already inited pikaday
pikaday.setMinDate(moment().add(2, 'days').toDate());
```

It allows me to pick a day 3 days from today. shouldn't it work the same as when I first started the plugin? today I'm having to do something like this to work as expected

```js
// already inited pikaday
pikaday.setMinDate(moment().add((dynamicDay - 1), 'days').toDate());
```

**Comment by rikkert** [comment]
Fixed with #262
