### ISSUE TITLE
disableWeekends and defaultDate does not work

### ISSUE THREAD

**Issue by thetutlage** [dbushell/Pikaday#257]
disableWeekends and defaultDate does not work while passing options

**Comment by jmeas** [comment]
`disableWeekends` isn't working for me at all.

**Comment by jmeas** [comment]
Nor does `disableDayFn` :frown:

I'm using the jQuery plugin, and I've verified that it's passing the appropriate options into Pikaday.

**Comment by jmeas** [comment]
> Nor does disableDayFn

o lol this is unreleased. The commit history seems a bit odd, but it's possible that `disableWeekends` is unreleased also.

**Comment by schoenkaft** [comment]
Same problem. Just found out the `master` on GitHub is more up-to-date than the latest release, which is `1.3.1`. So the `bower` version of  `1.3.1` does not match the apparent `master 1.3.1`, which is actually more like `1.3.2` if you ask me.

For anyone, to install the latest version with bower (and save as (non-dev-)dependency): `bower i -S https://github.com/dbushell/Pikaday.git#master`

**Comment by jmeas** [comment]
@schoenkaft many projects do development on master branch, so it's not *too* surprising that master is ahead of the last release. In any event, it's safer to use a commit sha. Master is subject to change in breaking ways without warning – commits are reliable.

**Comment by schoenkaft** [comment]
@jmeas valid point. Didn't see the last part of your latest comment, but commit sha should be safer, I agree. Valid point again.

So for install with bower: `bower i -S https://github.com/dbushell/Pikaday.git#b017d62c08defafb5e7e16f1b76cec2cf81a5b7a`

**Comment by rikkert** [comment]
Sorry for the confusion, I will make a 1.3.2 from master.
