### ISSUE TITLE
Remove !important rules

### ISSUE THREAD

**Issue by jmeas** [dbushell/Pikaday#258]
Using `!important` [in the stylesheet](https://github.com/dbushell/Pikaday/blob/master/css/pikaday.css#L191-L196) only makes it more difficult to override later. Lots of folks use linters that prevent them from using important, for instance.

**Comment by Saturate** [comment]
I agree, it should not be needed.

**Comment by rikkert** [comment]
Use theme to overwrite?

**Comment by jmeas** [comment]
> Use theme to overwrite?

what ya mean?

**Comment by benjibee** [comment]
I'd like to second this. I was quite surprised to see `!important` when I read through the stylesheet.

I had to rewrite the theme just so I could include it in my project and not fill my `gulpfile` with exceptions.
