### ISSUE TITLE
Code on NPM is out of date

### ISSUE THREAD

**Issue by jmcarp** [dbushell/Pikaday#261]
Installing from NPM seems to pull outdated code, even when specifying the current version (1.3.1). For example, the contents of https://registry.npmjs.org/pikaday/-/pikaday-1.3.1.tgz don't include the changes in 468a3751eff899fa05d2c1883fc4c2f730ca0add. It's possible there's something wrong on my end, but clearing my NPM cache had no effect. FWIW, installing with bower works fine.

**Comment by schoenkaft** [comment]
Should be now, since `1.3.2` was released due to my suggestion in https://github.com/dbushell/Pikaday/issues/257

Unrelated: `minDate` appears to broke since `1.3.2`. Will open an issue shortly.

**Comment by rikkert** [comment]
Use 1.3.2
