### ISSUE TITLE
Issues with Month / Year dropdown

### ISSUE THREAD

**Issue by franzos** [dbushell/Pikaday#264]
I've noticed the following:
1. When I download the source from Github, the Month / Year dropdown isn't working
2. When I download the ressources from https://dbushell.github.io/Pikaday/, Month / Year work just fine.

**Comment by davitv** [comment]
I even didn't know that it should work as a select...

**Comment by rsistermans** [comment]
@franzos How did you manage to fix it?

**Comment by rsistermans** [comment]
There's an e.preventDefault() on line 405 in the onMouseDown function that's causing this. It's been added since the demo version. If you remove this line it'll work.

**Comment by mjuniper** [comment]
I see this problem too since v1.3.0.

**Comment by rikkert** [comment]
Problem is fixed in 1.3,2
