### ISSUE TITLE
Include minified CSS & JS files for quick distribution.

### ISSUE THREAD

**Issue by pderksen** [dbushell/Pikaday#274]
Like other popular libraries. For both CSS & JS files. This would be helpful.

Maybe in a dist/ or min/ folder like Bootstrap or Moment.

**Comment by xdestiny** [comment]
Maybe, in addition to this, add the release version number to the pikaday.js so one can determine which version is in use.

**Comment by pderksen** [comment]
Agreed. See PR #275 :)

**Comment by jshah4517** [comment]
Agreed, please include minified version.

**Comment by eggyal** [comment]
@rikkert: Could you add a comment to explain why this was closed without being resolved?  Is it "wontfix"?

**Comment by rikkert** [comment]
Yes, won't fix. Also discussed in #275.
Use a module system and let that minify all your files.

**Comment by dsnoeck** [comment]
Otherwise, minified version can be directly included from https://cdnjs.com/libraries/pikaday
i.e: https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.4.0/pikaday.min.js
