### ISSUE TITLE
`_onMouseDown` event not being set if `ontouchend` is defined

### ISSUE THREAD

**Issue by TW80000** [dbushell/Pikaday#276]
I was having a problem where after I clicked on a day in the calendar, the input field would not be updated with the date string.

I set a few breakpoints and realized that none of the events were being called for clicking on the calendar.  So I looked at where they were set and noticed that on line 533 it checks if `ontouchend in document` is true and sets the event to that if it is. This effectively overrides the `onmousedown` event, which it needs to work in chrome for desktop. 

I believe you may need to do more sophisticated checking to define the events.

Forgive me if this is poorly done or explained. This is my first issue / bug fix. If you need any more information I'd be happy to help.

**Comment by rsistermans** [comment]
I was having the same problem and found the solution in the same line. (Windows touchscreen laptop and Chrome browser).

The demo was working for me: http://dbushell.github.io/Pikaday/ but the pikaday script here differs from the version in GIT. Using the former fixes the problem for Windows touchscreen users

Demo version:
addEvent(self.el, 'mousedown', self._onMouseDown, true);

Git version:
addEvent(self.el, 'ontouchend' in document ? 'ontouchend' : 'mousedown', self._onMouseDown, true);

**Comment by smkt** [comment]
I had the same problem and I fixed it by removing 'on' prefix from 'ontouchend':

addEvent(self.el, 'ontouchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true);

Now the touchend event is properly registered and pikaday works as expected both on mobile and desktop browsers.

**Comment by scttcper** [comment]
Ran into this as well.
addEvent(self.el, 'ontouchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true); didn't work on the laptops with touch screen + using a mouse.

Only this has worked so far for everything.
```js
addEvent(self.el, 'mousedown', self._onMouseDown, true);  
```

**Comment by whather** [comment]
@scttcper @smkt it was initially:

```
addEvent(self.el, 'mousedown', self._onMouseDown, true);
```

but then was changed to 

```
addEvent(self.el, 'ontouchend' in document ? 'ontouchend' : 'mousedown', self._onMouseDown, true);
```

from this commit https://github.com/dbushell/Pikaday/commit/c4c9037767759ca7cccbf3b43cd8205cd560319b

Wondering if it should be this instead? (Notice ontouchend in BOTH places were changed to touchend):

```
addEvent(self.el, 'touchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true);
```

Has anyone tried this? @smkt is this what you meant? I have a customer who is experiencing this problem and I'm wondering what it should be changed to...

**Comment by lochstar** [comment]
addEvent(self.el, 'touchend' in document ? 'ontouchend' : 'mousedown', self._onMouseDown, true);
AND
addEvent(self.el, 'mousedown', self._onMouseDown, true);

Both work in Chrome with a touchscreen.

**Comment by rikkert** [comment]
So is it correct right now?

**Comment by whather** [comment]
No, I had to change back to: addEvent(self.el, 'mousedown',
self._onMouseDown, true);

This fixes customers using a Microsoft Surface with a mouse.

**Comment by scttcper** [comment]
My findings were the same as @whather. Was broken on touchscreens in chrome using a mouse, with my previous post being what we're still using.

**Comment by duizendnegen** [comment]
Listening to both mousedown and touchend might end up being a solution.
In my experience mousedown is fired on iOS if the css `cursor: pointer;` is set, that could also help.
