### ISSUE TITLE
Use official, more updated Moment.js package instead

### ISSUE THREAD

**Issue by fungilation** [dbushell/Pikaday#279]
https://atmospherejs.com/momentjs/moment

I use this in my app to get the latest version. Having dependencies on both have version conflict.

The 2 packages at current versions:

momentjs:moment@2.9.0
mrt:moment@2.8.1

**Comment by rikkert** [comment]
Does pikaday not work with latest?

**Comment by rikkert** [comment]
I think your problem is from meteor and not pikaday.
