### ISSUE TITLE
Unable to use a default date in Safari (both OS X and iOS)

### ISSUE THREAD

**Issue by bitcalc** [dbushell/Pikaday#286]
~~~
pickerEnd = new Pikaday({
	field: document.getElementById('pikadayEnd'),
	firstDay: 1,
	defaultDate: new Date("2015-03-31T23:59:59+0100"),
	setDefaultDate: true,
	minDate: new Date('2015-01-01'),
	maxDate: new Date(),
	format: 'LL',
	yearRange: [2015, 2050],
	bound: false,
	container: document.getElementById('pikadayEndContainer'),
});
~~~

When the page is loaded, the `field` inputs are blank and the calendar doesn't have any dates selected.

The code works fine on Chrome (OS X), I'll have to test other browsers though...

**Comment by bitcalc** [comment]
Related? https://github.com/dbushell/Pikaday/issues/201

**Comment by bitcalc** [comment]
I have a workaround:

~~~
pickerEnd = new Pikaday({
    ...
});

pickerEnd.setMoment(moment("2015-03-31T23:59:59+0100"), true); // Safari BUGFIX
~~~

**Comment by rikkert** [comment]
Any clues?

**Comment by bitcalc** [comment]
Safari doesn't accept `new Date("2015-03-31T23:59:59+0100")` on the console, so it would mean I'm passing an invalid date when calling `new Pikaday`. I had forgotten about this actually, we can close it as it's Safari's problem not Pikaday's... (just need to change date specification or use Moment.JS)
