### ISSUE TITLE
For disabled date, date is clickable in Internet explorer 8

### ISSUE THREAD

**Issue by rock2k3CS** [dbushell/Pikaday#288]
When we use disable  weekends feature of pikaday, the date buttons for disabled date is still clickable in IE8, as the css .is-disabled .pika-button has style 'pointer-events:none;' is only supported for IE9 and above.
As pikaday is supported for IE7 and above, please provide solution.

**Comment by esbenam** [comment]
This is still an issue.

There is an error in the _onClick method when testing whether the button is disabled. 

https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L430

`if (!hasClass(target, 'is-disabled'))`

The is-disabled class is on the parentNode, so the code has to read

`if (!hasClass(target.parentNode, 'is-disabled'))`

I haven't read through the hole thing but it seems to do the trick.

Maybe this could be fixed on master, @dbushell?
