### ISSUE TITLE
picker.setDate +1 substracts days

### ISSUE THREAD

**Issue by VisualBean** [dbushell/Pikaday#289]
$(document).on('click', '#next-date', function(){
            var field = document.getElementById('datepicker');
            picker.setDate(picker.getDate() +1);
            field.innerHTML =(picker.getDate());
        });

The above code substracts 1 day each time next-date is pressed.

**Comment by rikkert** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
