### ISSUE TITLE
Pikaday not working on mobile browsers

### ISSUE THREAD

**Issue by shahvikram24** [dbushell/Pikaday#301]
As discussed in #68 ,
I tried to change the events. but still not working.
addEvent(self.el, 'touchend' in document ? 'touchend' : 'click', self._onClick, true);

Still having issues.

**Comment by RobbieLePommie** [comment]
Line 534: add

        addEvent(self.el, 'touchstart', self._onMouseDown, true);

Line 1016: add

            removeEvent(this.el, 'touchstart', this._onMouseDown, true);

(Would do a pull request, but not worth it for two lines...)

**Comment by RobbieLePommie** [comment]
Update: I notice in another version this has been addressed more reputably with 

            addEvent(self.el, 'ontouchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true);

However the corresponding line 1032.

             removeEvent(this.el, 'mousedown', this._onMouseDown, true);

needs to also be adjusted to 

             removeEvent(this.el, 'ontouchend' in document ? 'touchend' : 'mousedown',this._onMouseDown, true);

When that's implemented, this issue can be closed, I think.

**Comment by NickyYo** [comment]
Why would you ever want to use the html version of a date picker on mobile anyways!?
Just use jQuery or something to change the input type to date to initiate the native date picker for mobiles.

**Comment by espen** [comment]
Many reasons @NickyYo. Date range, theme, show additional information. And IMO most implementations of native date pickers aren't that good.

**Comment by mortargrind** [comment]
@NickyYo are you serious? 

1-) This is the browser support for input type=date: http://caniuse.com/#search=date
2-) Because customer wants a calendar, not a native datepicker.

Anyways, I think "click" event is sufficient both for touch and non-touch devices.

**Comment by RobbieLePommie** [comment]
@nathancahill @rikkert   Thanks for the fix
