### ISSUE TITLE
Doesn't work on Chrome

### ISSUE THREAD

**Issue by VisualBean** [dbushell/Pikaday#303]
Try your own example in Chrome - Not able to select date.

**Comment by VisualBean** [comment]
Fixed by finding issue: 276
```javascript
changed addEvent(self.el, 'ontouchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true);
to 
```javascript
addEvent(self.el, 'mousedown', self._onMouseDown, true);

**Comment by HerrGrumps** [comment]
it works for me in Chrome - I am using the jquery method to add it to my page, would that have any bearing on it?

**Comment by ianwitherow** [comment]
That fixed it for me, thanks!

**Comment by goggledefogger** [comment]
That fixed it for me too! I was struggling over this problem, and there are other issues that are maybe dupes of this? 327, 324.

Does this fix have any negative side effects? Or can you incorporate it into the next release?
