### ISSUE TITLE
Toggle calendar visibility when trigger is clicked.

### ISSUE THREAD

**Issue by ngryman** [dbushell/Pikaday#305]
Hey,

When specifying a `trigger` element (other that `field`), I can't find a clean way to toggle calendar's visibility when clicking the `trigger` element.
Is it possible to add an option for this?

Thanks!

**Comment by RobbieLePommie** [comment]
If trigger is set, the events are automatically attached to the element - so you don't need to handle specifically.

If you do need to handle specifically, there are the "show()" and "hide()" functions that are exposed and available, you can trigger one of those. Is that what you refer to? Or something deeper?

**Comment by ngryman** [comment]
`trigger` does not handle hiding the calendar if I click again on the element, it just opens the calendar, that's it.

I've tried to handle this with `show()` and `hide()` but then I lose the ability to position the calendar relatively to the element.

What I would like is that `trigger` would be able to toggle the calendar, instead of just showing it.

**Comment by aft-luke** [comment]
:+1: on this. Overall I would say this library is really intrusive - forcing you to pick some permutation of container, or toggle, or field, etc. otherwise it Just Doesnt Work®. A small improvement would allow the trigger to be able to both show() and hide() the picker.

**Comment by nathancahill** [comment]
:+1: too. Just ran into this when the element is not a field.
