### ISSUE TITLE
Bower version is not accurate

### ISSUE THREAD

**Issue by mortargrind** [dbushell/Pikaday#323]
Hi,

When i do "bower install pikaday" bower gets the "1.3.2" version but the code is not same with the master branch. (for example it does not have the "theme" functionality").

**Comment by nathancahill** [comment]
There hasn't been a new release yet. You can do this to get the master branch:

    bower install https://github.com/dbushell/Pikaday.git

**Comment by mortargrind** [comment]
Yeah, but the currently newest features are present on the README file here but when people downloads pikaday via bower (they would most probably just type bower install pikaday) they don't get the version that is presented on the master's README. I know this is not a big deal and i can get the latest version as you said but: If a feature is implemented, tested, documented & released it should be available on all the delivery channels, otherwise its inconsistent and confusing for the users.
