### ISSUE TITLE
Demo vs Firefox. Clicks cause the date picker to be hidden.

### ISSUE THREAD

**Issue by ollicle** [dbushell/Pikaday#324]
Steps to reproduce:

1. Load: http://dbushell.github.io/Pikaday/ in Firefox (37.0.1)
2. Click or focus input – widget displays as expected
3. Click: 

    a day of month, back/next arrows: widget hides & input remains blank

    the current month/year: month select displays momentarily & widget hides

**Comment by benelliott** [comment]
Can confirm this happens on Chrome v42 as well!

**Comment by quintenvk** [comment]
+1 on Firefox 38.0.5, OS X build.

**Comment by ZeStrid3r** [comment]
Firefox sets default "ontouchend" event in document object, so the "onmousedown" event isn't created cause to the line 546 :
```
546    addEvent(self.el, 'ontouchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true);
```
Try to replace it by :
```
if('ontouchend' in document)
	addEvent(self.el, 'touchend', self._onMouseDown, true);
if('onmousedown' in document)
	addEvent(self.el, 'mousedown', self._onMouseDown, true);
```

Works on Firefox 39.0.
