### ISSUE TITLE
Date range option?

### ISSUE THREAD

**Issue by nathancahill** [dbushell/Pikaday#332]
This was talked about a couple years ago (#5) and partially implemented in #300, and I think it's a pretty good idea. I wrote an implementation here: 42777b4, and an example here: http://nathancahill.github.io/Pikaday/examples/date-range.html

If this is something you'd be interested in I can submit a pull request. Most of the logic is handled outside of the library: c69ea6c, I only added hooks for styling the start, end and range calendar days.

__EDIT__

@N1ck took this a step further, adding styles for start and end dates. It now looks like this:

![](http://i.imgur.com/yXSMDd6.png)

**Comment by JKGisMe** [comment]
That is lovely.

**Comment by rikkert** [comment]
The fact that it is low impact is really nice, would be great to have a PR.

**Comment by nathancahill** [comment]
Great! I'll submit one. It relies on #312, can we get that merged first?

**Comment by rikkert** [comment]
Done

**Comment by nathancahill** [comment]
Thanks @rikkert. Opened #337

**Comment by lukaszsobiech** [comment]
Hi is it possible to set pikaday range with only one input field? 

1. Click input, show the calendar
2. Click start date
3. Click end date (within the same calendar)

Thanks for your feedback

**Comment by jaschaio** [comment]
@lukaszsobiech did you find a way?

**Comment by niksajanjic** [comment]
This is awesome. I'll just add one thought here. It would be nice to have it sort of "live". If you take a look at https://www.booking.com page calendar, while you move your mouse over the calendar it will update range (in grayish color) even before you select the second date.

But I believe this would be calling range calculations way to many times (on every mouse movement through calendar) and in the end it is not adding that much of a feature for that amount of hustle.

**Comment by lukaszsobiech** [comment]
@jaschaio yes have a look at element ui date range... its a good start, I needed something more complex with a state management

**Comment by robinbonnes** [comment]
> Hi is it possible to set pikaday range with only one input field?
> 
> 1. Click input, show the calendar
> 2. Click start date
> 3. Click end date (within the same calendar)
> 
> Thanks for your feedback

Is there any update on this? Maybe its easier to drag from start date to end date or hold the shift key.
