### ISSUE TITLE
Version inconsistency when installed with Bower

### ISSUE THREAD

**Issue by gokceno** [dbushell/Pikaday#338]
This is kinda weird. When I run a bower update with bower.json containing:
```
{
	"pikaday": "1.3.2"
}
```
an older version is downloaded, without the theme support. I can't be sure if it's an older version but it's a different file.

I cleared the bower cache but no luck.

Any thoughts?

**Comment by nathancahill** [comment]
See #323

**Comment by gokceno** [comment]
Thanks!
