### ISSUE TITLE
Selectable range doesn't always update with set Max/MinDate

### ISSUE THREAD

**Issue by jasontibbitts** [dbushell/Pikaday#340]
I'm having an odd problem where sometimes the range of dates that appear to be selectable doesn't update after calling setMinDate and setMaxDate.  The original date range will still highlight, but as soon as you click one of them the selection appears to clamp to the new range and the visible set of selectable dates updates.

This is completely repeatable in my complete application but I'll try to put together a minimal test case.  My application basically pulls a set of data from the server (via ajax) and updates a small calendar to show the endpoints of the data set.

I'm running the current git version (9f2b3b11530f48d4cea440f11e2ef51f60c0e870 as I type this).  I see the last commit has something related so I'll try calling setStart/EndRange as well and see if it makes any difference.

**Comment by nathancahill** [comment]
If you can put together a JSFiddle I'll take a look at it. You'd have to call `setStartRange`/`setEndRange` if you're updating the _selected_ dates, and `setMinDate`/`setMaxDate` to update the _selectable_ dates.

The selected date range does not update automatically when minDate and maxDate are changed.

**Comment by nathancahill** [comment]
It sounds like you're probably seeing the same behavior as this example: http://jsfiddle.net/1w43qxvb/2/

**Comment by jasontibbitts** [comment]
Not exactly.  My picker is bound to a hidden field and never disappears, so I think that it makes odd behavior more visible.  Try this: http://jsfiddle.net/1w43qxvb/3/

**Comment by nathancahill** [comment]
When you use `bound: false` you have to manually redraw the picker. Change `picker.show()` to `picker.draw()` and it should work: http://jsfiddle.net/1w43qxvb/5/

**Comment by jasontibbitts** [comment]
Ah, thanks.  My fault for missing this in the docs.

**Comment by nathancahill** [comment]
I don't think it's in the docs. There should probably be a note about that, or the behavior should be changed to work the same as `bound: true`
