### ISSUE TITLE
library collides with ember-i18n

### ISSUE THREAD

**Issue by mylen** [dbushell/Pikaday#344]
> Ember      : 1.12.0
> Ember Data : 1.0.0-beta.18
> jQuery     : 1.11.3
> ember-cli-datepicker: 2.0.1
> ember-cli-datepicker: 2.0.1
> ember-i18n: 4.0.0-beta.2

in function: 
```js
        for (arr = [], i = 0; i < 12; i++) {
            arr.push('<option value="' + (year === refYear ? i - c : 12 + i - c) + '"' +
                (i === month ? ' selected': '') +
                ((isMinYear && i < opts.minMonth) || (isMaxYear && i > opts.maxMonth) ? 'disabled' : '') + '>' +
                opts.i18n.months[i] + '</option>');
        }
```

opts.i18n is set to service:i18n

Actually when you do :

```js
    ['bound', 'position', 'reposition', 'format', 'firstDay', 'minDate',
     'maxDate', 'showWeekNumber', 'isRTL', 'i18n', 'yearSuffix',
     'showMonthAfterYear', 'numberOfMonths', 'mainCalendar'].forEach(function(f) {
       if (!Em.isEmpty(that.get(f))) {
         pickerOptions[f] = that.get(f);
       }
     });
```

i18n is already in the context because injected by the i18n component. You might want to use a private name like _i18n in order to prevent collisions.

I've changed the i18n value to _i18n and I do not have any problem anymore.

**Comment by nathancahill** [comment]
I'm surprised that ember-i18n is injected into Pikaday's `opts` object. That seems more like a problem with ember-i18n than with Pikaday.

**Comment by mylen** [comment]
Well, ember-i18n is injected in all components and model in my code:

```js
export default({
  name: 'i18n',

  initialize: function(registry, application) {
    application.inject('model', 'i18n', 'service:i18n');
    application.inject('component', 'i18n', 'service:i18n');
  }
});
```

The thing is you are using an i18n object in your code but do not use the i18n library, you could either  call your object with a private name like _i18n, because I don't see the point of using the i18n word and provide only English... 

I might as well inject i18n as a per use bases. But as ember is going all components soon, it would be a pain in the ass to inject it manualy.

**Comment by mylen** [comment]
The issue might be with ember-cli-datepicker
