### ISSUE TITLE
[Q] How to unset a date?

### ISSUE THREAD

**Issue by gaydenko** [dbushell/Pikaday#373]
What is supposed way to unset a date and to clear an input field?

**Comment by gaydenko** [comment]
Aha, have looked at the code - it is legal to use falsy argument in `setDate()` call. Probably it can be added to README.md.

**Comment by Rask** [comment]
Does not seem to be working on my end. Calling `setDate(false)` does *something*, but the calendar is not cleared.

Additionally calling `pikaday.destroy()` does not somehow clear disabled (selected) days in the calendars.
