### ISSUE TITLE
Month/Year only

### ISSUE THREAD

**Issue by a7mad-12** [dbushell/Pikaday#376]
Is it possible to show only month and year ?!

**Comment by nathancahill** [comment]
No

**Comment by godshades** [comment]
hi how to overwrite onDraw  function, i have same issue

**Comment by Peripona** [comment]
For Overwriting onDraw Function. you can do it on single object that you get when you instantiate ` ` ` var obj = Pikaday({}); and then obj.draw = your function(){}..  ` ` ` 
you should try finding others ways too.
