### ISSUE TITLE
Show years for Buddhist calendar

### ISSUE THREAD

**Issue by dogrocker** [dbushell/Pikaday#384]
Hello, I trying to use this Pikaday to Buddhist calendar but don't know how to edit it.

For Buddhist calendar just plus 543 for the year

`uses Buddhist-Era (B.E.) that is 543 years greater than Christian-Era (C.E.).`

2015 + 543 = 2558

I try to edit 

```
year: date.getFullYear() + 543
```

It generate me 2558 but the week and date is not collect.

data that collect:

`29 Aug 2015` is `Sat` so `29 Aug 2558` is `Sat` too.

not collect:

`29 Aug 2015` is `Sat` but `29 Aug 2558` is `Sunday` that not collect.

Thanks.

**Comment by dogrocker** [comment]
O.K. now, I hot fixed it. If I have enough time I will refactor the code and PR.
Thanks.

**Comment by rikkert** [comment]
Nice, you probably want to use [momentjs](http://momentjs.com) for such things.
