### ISSUE TITLE
field with Pikaday is automatically going backwards by one day everytime record is edited.

### ISSUE THREAD

**Issue by memoht** [dbushell/Pikaday#39]
I have a field called **last_issue** on a rails model. If a date exists in the the last_issue field, every time you edit the record, the date appears to be dropping back by one day. Edit a record seven times and your date will be off by a week from where it started.

I am using the following setting for this field:
  `picker = new Pikaday(field: $("#issue_date")[0])`

Any suggestions as to why this is happening?

**Comment by TimGeyssens** [comment]
Still having this issue with latest version.. seems to have to do with timezone setting, not sure how to fix any help appreciated

**Comment by eybarta** [comment]
I'm also experiencing a similar issue.. 
I'm using moment() and have been until now no problems..
When adding moment-timezone.js and setting it (e.g: moment.tz.setDefault('America/New_York');) I'm getting the same problem as described above, the display dates for input fields after init is a day back.. Am I doing something wrong or is this a bug? thnx

**Comment by sdbondi** [comment]
Note that when you have a date (like that returned from `getDate()`) it will have the timezone of your computers clock. When calling `date.toUTCString()` the date will be in the `GMT` timezone which may confuse some people into thinking pikaday has chasen the previous day. 

`.getDate()`
`Wed Dec 02 2015 00:00:00 GMT+0200 (SAST)`

`.getDate().toUTCString()`
`"Tue, 01 Dec 2015 22:00:00 GMT"`

**Comment by gregmatthewcrossley** [comment]
For anyone using Ruby/Rails, I found that adding `.strftime("%a %b %d %Y")` to a Date fixed the issue.

**Comment by jacquesporveau** [comment]
This worked for me. In the setDate function of Pikaday.js add:

```
if (typeof date === 'object') {
  var utc = date.getTime() + (date.getTimezoneOffset() * 60000 + 500);
  date = new Date(utc)
}
```

I am adding 500 milliseconds because sometimes the calculation is a little off and since my app is saving dates and midnight it would occasionally show the wrong day if the calculation came back slightly short.
