### ISSUE TITLE
Incorrect date is picked

### ISSUE THREAD

**Issue by averrips** [dbushell/Pikaday#399]
We are experiencing a serious bug with the latest version.

The datepicker often picks the wrong day (a day earlier), but not all the time. Try to pick May 20th 1959 for example: the result will be 19-05-1959. Sometimes whole months are affected, sometimes only specific days in the month.

This was tested in Chrome and Safari. Our timezone is Europe/Amsterdam.

**Comment by averrips** [comment]
I closed this since I found out that it's not strictly a bug. It has to do with the default timezone of momentjs. Still, since momentjs is supported it would be probably best to not break when a default timezone is set. It's very user unfriendly to have the date changed after selecting the right one... :)

**Comment by laynegt** [comment]
I'm having the same issue.  I believe there is a fix inside pikaday.  Pikaday sets the date to midnight local time (native `Date` behavior), so we just need to translate the moment object to local time.

```
toString: function(format)
{
  return !isDate(this._d) ? '' : hasMoment ? moment(this._d).format(format || this._o.format) : this._d.toDateString();
},
```
changes to
```
toString: function(format)
{
  return !isDate(this._d) ? '' : hasMoment ? moment(this._d).local().format(format || this._o.format) : this._d.toDateString();
},
```
Happy to submit a PR if correct.
