### ISSUE TITLE
Pikaday not working in mozilla firefox

### ISSUE THREAD

**Issue by sreelalks** [dbushell/Pikaday#404]
I just try to pick a date in Pikaday, when i click on a calendar pop-up, calendar  fade out the text filed still empty..
im using this url: http://dbushell.github.io/Pikaday/

**Comment by HCBen** [comment]
Same here. Using FF 40.0.3

**Comment by serneelsalexis** [comment]
+1

Broken on last FF.

**Comment by thekeogh** [comment]
Likewise, can see the calendar appear, but selecting a date does nothing. FF 41.0.2 here

**Comment by jopotts** [comment]
I think this is a cross-browser issue. There's something subtle that occasionally breaks on minor browser updates. Relates to this: https://github.com/dbushell/Pikaday/issues/406
