### ISSUE TITLE
r.js optimizer fails to load moment in the proper order.

### ISSUE THREAD

**Issue by Jmeyering** [dbushell/Pikaday#408]
It seems that Pikaday does not include moment in a way that can be managed via the r.js optimizer.

from http://requirejs.org/docs/optimization.html
```
The optimizer will only combine modules that are specified in arrays of string literals that are passed
to top-level require and define calls, or the require('name') string literal calls in a simplified
CommonJS wrapping. So, it will not find modules that are loaded via a variable name
```

And due to the fact that Pikaday requires moment to actually be physically LOADED before itself the r.js optimizer at times does not order things properly and Pikaday ends up formatting everything badly. 

A solution may be to use a string literal to require moment rather than variable, however reading #395 I would agree that a better solution would be to have a version that explicitly requires moment rather than loading as a dependency.

**Comment by rikkert** [comment]
Lets continue in #395
