### ISSUE TITLE
Next and Prev. are not disabled

### ISSUE THREAD

**Issue by b-b3rn4rd** [dbushell/Pikaday#410]
Next and Prev. buttons with 'is-disabled' class still allow to navigate between months.

It seems that the problem was introduced in 1.3.3 version. https://github.com/dbushell/Pikaday/blob/1.3.3/pikaday.js#L420

Best Regards,
Bernard

**Comment by Alexwijn** [comment]
Any progress?

**Comment by b-b3rn4rd** [comment]
I submitted PR, have not heard back...

**Comment by b-b3rn4rd** [comment]
PR has been merge, closing the ticket.
