### ISSUE TITLE
disableDayFn blocking out Tuesdays instead of Mondays

### ISSUE THREAD

**Issue by MikkyX** [dbushell/Pikaday#420]
I have the following array of dates:
    
    var disallowedDates = [
    	'2015-01-01','2015-12-25','2015-12-26','2016-01-01','2016-12-25','2016-12-26','2015-12-28','2016-03-25','2016-03-28','2016-05-02','2016-05-30','2016-08-29','2016-12-27'
	]

and my disableDayFn function is as follows:

    disableDayFn: function(theDate) {
        theDate = theDate.toISOString().split('T')[0];
            
        if (disallowedDates.indexOf(theDate) != -1) {
            console.log(theDate+' - BLOCKED');
        } else {
            console.log(theDate);
        }
            
        return (disallowedDates.indexOf(theDate) != -1)
    }

Saturdays and Sundays are also blocked via disableWeekends: true.

You will notice I have a console.log statement in the disableDayFn - this correctly returns, for example '2016-03-28 - BLOCKED': 
![screen shot 2015-10-06 at 16 30 30](https://cloud.githubusercontent.com/assets/7023132/10313458/a2b84e5c-6c47-11e5-94b8-44deb13f8f0a.png)

 - but on the calendar it's the 29TH - the Tuesday / day after, which is blocked instead. The 28th CAN be selected: 

![screen shot 2015-10-06 at 16 30 16](https://cloud.githubusercontent.com/assets/7023132/10313475/b3f42b14-6c47-11e5-92f0-adfb99fc4426.png)

For other days of the week, e.g. 2016-03-25 (a Friday), the correct date is blocked as expected.

Have I done something wrong or is there a bug here?

**Comment by tomasswood** [comment]
I can also reproduce this:

`[ '2015-11-26','2015-11-27','2015-11-28','2015-12-29','2015-12-30','2015-12-31','2016-01-01','2016-01-02' ]`

All the dates the day after will be blocked. Eg, Nov/27, Nov/28, Nov/29

**Comment by rikkert** [comment]
Definitely a bug, not sure yet what is going on.

**Comment by rikkert** [comment]
It is a bug in your disableDayFn implementation:
new Date(2016, 2, 29).toISOString() -->
"2016-03-28T22:00:00.000Z"
Try using getDate and getMonth or toString instead.

**Comment by recruitname** [comment]
hi is there same function to special days ? with we can give a class it to colored ?
