### ISSUE TITLE
Cannot read property 'months' of undefined

### ISSUE THREAD

**Issue by leandroruel** [dbushell/Pikaday#421]
not sure if the owner of this repo is still active here, given the number of issues opened here, but i search a lot to try find a solution for this... in pages where i'm not using an input with calendar i get the following error: **Cannot read property 'months' of undefined** :suspect: 

if anyone here can give me a light would be great. thank you ( i will keep searching for a solution)

the error point me to this line:
https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L352

opts.i18n.months[i] + '</option>');

**UPDATE:**
i'm trying run my script only in pages with calendar, but i need a way of this script run only when i need

**Comment by rikkert** [comment]
Checkout the container.html example.

**Comment by leandroruel** [comment]
i fixed it a few months later, but thanks for answer me.
