### ISSUE TITLE
Moments and Pikaday with require.js and r.js optimizer

### ISSUE THREAD

**Issue by lukas-comstock** [dbushell/Pikaday#424]
Hello,

I am wondering if there are any examples of how to ensure that Moments is loaded before Pikaday when using require.js and the r.js optimizer.  I have an application that I am working on currently that is using r.js optimizer to combine and minify all of the scripts and after doing so, I lose the ability to use the format property on the Pikaday object to format the date the way that I would like it.

Any suggestions?

**Comment by rikkert** [comment]
This is mostly likely due to the fact moment is an optional dependency for moment.
Try requiring moment in your app.js.
