### ISSUE TITLE
Cannot embed calendar without a field

### ISSUE THREAD

**Issue by jakeprime** [dbushell/Pikaday#426]
I'm not sure if this is a bug or desired functionality, but I am not able to embed the calendar without specifying a field. I want to specify the container to embed it into and then use the onSelect callback to process the date.

```
var picker = new Pikaday({
  bound: false,
  container: document.getElementById('DatePicker'),
  onSelect: function(date) {
    console.log(date);
  }
});
```

I have managed to get this to work by changing the following code:

```
// pikaday.js
// line 550
        if (opts.container) {
            opts.container.appendChild(self.el);
        } else if (opts.bound) {
            document.body.appendChild(self.el);
        } else if (opts.field) {
            opts.field.parentNode.insertBefore(self.el, opts.field.nextSibling);
        }
        if (opts.field) {
          addEvent(opts.field, 'change', self._onInputChange);
          if (!opts.defaultDate) {
              if (hasMoment && opts.field.value) {
                  opts.defaultDate = moment(opts.field.value, opts.format).toDate();
              } else {
                  opts.defaultDate = new Date(Date.parse(opts.field.value));
              }
              opts.setDefaultDate = true;
          }
        }
```

Disclaimer: This does work for me, but I haven't thoroughly tested everything so not sure if this has any side effects.

**Comment by rikkert** [comment]
Check out the container.html example.

**Comment by jakeprime** [comment]
The container.html example specifies a field, and won't work without it. I didn't have a field, just a container, and the above javascript edit made that work for me.

**Comment by GarPit** [comment]
+1
