### ISSUE TITLE
When can we expect the fixes for touch device support to be released?

### ISSUE THREAD

**Issue by stringbeans** [dbushell/Pikaday#427]
I see in the change log you have:

1.4.0 - TBA
Fix touch device support, see #374, #276, #301, #303, #324, #366 and #386

Do you have a timeline on when these fixes will be released? We have customers here that are experiencing issues with this and it looks like those fixes will fix the issues.

Cheers,

**Comment by jopotts** [comment]
@rikkert It would be amazing if you could merge these fixes in. I think it's the same issue causing #404 and #406 too. Thanks!

**Comment by jopotts** [comment]
I just realised that the fixes are in master already, so it's just a version number bump that's required. I think that would eliminate the chatter in the various issue comments about the same thing.

**Comment by stringbeans** [comment]
@dbushell any word?

**Comment by rikkert** [comment]
1.4.0 is released and published
