### ISSUE TITLE
Throw exception, if Pikaday is initialize twice using the same Element

### ISSUE THREAD

**Issue by j6s** [dbushell/Pikaday#429]
If (on accident) Pikaday is initialized twice for a single DOM Element, the two instances will create a loop, firing change events back and forth (and not stopping, because `e.firedBy` is not `self`). 

Granted, the fault in this case is not in the Library, but in the developer using the Library, but simply throwing an exception, if a user tries to initialize Pikaday multiple times on the same Element would make debugging easier

**Comment by rikkert** [comment]
Can't reproduce the error.

**Comment by j6s** [comment]
You can see what I am describing very clearly in this pen: http://codepen.io/thephpjo/pen/pjqavp

If you select a date and have a look in the devtools you will see the instances `ping`ing and `pong`ing the event back and forth until the loop is stopped because the max callstack size was exceeded

**Comment by rikkert** [comment]
I see the problem when there is an onSelect.
Not sure how we can easily detect this.

**Comment by j6s** [comment]
There are 2 potential ways of tackling this:

1. Throw an exception if Pikaday is initialized on the same element twice (this is the solution I originally proposed)
However, the problem here is keeping track of the instances and the DOM Objects that are referenced.

2. Tweak the `firedBy` detection
If I remember correctly you are checking if `e.firedBy` is the current instance of Pikaday (which is why there is a loop since 2 instances are firing the event). If instead you check `e.firedby instanceof Pikaday` it would have the same effect but would not cause a infinite loop

**Comment by rikkert** [comment]
Thanks. I like the second option best. 
I'll try to implement it asap.

**Comment by dogui1718** [comment]
@j6s  Hi! Just now I have this same issue. I am using Pikaday in a form wich is use it for write articles. When I choose a date, everything is normal but, when I try to change it many times the browser frozen. Now I am trying to init a new instance everytime when the form is open and destroy it when the form is close it but, this doesn't work. My code in js below, I don't know if it is well. (I am using vue.js):

datepicker: function(p){
            var picker = '';
            if(p == 'init'){
                    picker = new Pikaday({
                    field: document.getElementById('datepicker'),
                    //minDate: new Date(),
                    //format: 'DD-MM-YYYY'
                });
            }else if(p == 'destroy'){
                picker.destroy();
            }
        }

@rikkert did you fix this issue?

**Comment by dogui1718** [comment]
I already fix my problem, now I create an instance of Pikaday when the document is ready and done! Thank you!

**Comment by chethan1095** [comment]
can we use only time in pikaday if yes how to use it in 12 hours format

**Comment by Tesnor** [comment]
Don't understand... Can you share a working example of a function?
