### ISSUE TITLE
New min/max dates for pickers in containers require hide and show

### ISSUE THREAD

**Issue by sobelk2** [dbushell/Pikaday#432]
I have a picker rendered into a container, and I routinely change `minDate` and `maxDate` using `picker.setMinDate()` and `picker.setMaxDate()`. However, by default, the new `minDate` or `maxDate` does not take effect until I navigate to a new month in the picker. The workaround for this is to hide and show the picker immediately after setting a new `minDate` or `maxDate`. I do not believe this should be necessary. This bug only occurs for pickers rendered into a container.

**Comment by nathancahill** [comment]
Good call, I'll take a look at this. Should be an easy fix.

**Comment by sobelk2** [comment]
Thanks!
