### ISSUE TITLE
Missing documentation for `draw()`

### ISSUE THREAD

**Issue by rask** [dbushell/Pikaday#435]
I think that the `draw()` method of the Pikaday class should be documented better.

A speed skim to the "available methods" section shows no info on this method, though it should be used instead of `show()` when the calendars are initialized in `bound: false` mode (e.g. in a separate container).

I ran into issued with a date range picker system with two calendars in separate containers, where the other calendar would not update to reflect changes to the other.

**Comment by rikkert** [comment]
I would be glad to accept a PR for this.
