### ISSUE TITLE
CSS ".is-selected" selector clashes with other projects

### ISSUE THREAD

**Issue by loicloicloicloic** [dbushell/Pikaday#436]
I just spent a good half hour scratching my head on this one...
Couldn't figure out why all the days were selected (".is-selected" css class)
Turns out the ".is-selected" class name is used a lot, in my case the datepicker was inside a javascript slider thingy which also used that class name to style the currently selected "slide"

So I just changed the CSS selector on line 176 of pikaday.css to:
.pika-single .is-selected .pika-button { }

Pretty minimal issue but worth mentionning

Love pikaday

**Comment by rikkert** [comment]
Thanks.
