### ISSUE TITLE
Feature Request: Show days preceding and following the current month

### ISSUE THREAD

**Issue by LordZardeck** [dbushell/Pikaday#438]
For our app we would like the empty cells before and after the current months days to show the days of the preceding and following month. This functionality is not implemented, and would be great if it was available. I'd be willing to extend the code to enable this if you would accept a PR for it.

**Comment by nathancahill** [comment]
See #381

**Comment by LordZardeck** [comment]
@nathancahill Thanks for that. I hope that can be accepted soon. If there is anything i can do to help, let me know.
