### ISSUE TITLE
Ability to prevent user from entering a date via its keyboard

### ISSUE THREAD

**Issue by QuentinFchx** [dbushell/Pikaday#440]
Hi,
Would it make sense to add an option to prevent users from entering a date through their keyboard?
I would like to force them to use the picker (preventing numpad keys), without disallowing navigation keys (arrows, tab).
I can provide a PR if the feature is relevant to you.

**Comment by rikkert** [comment]
Without or with a disabled input field this is already possible.

**Comment by jaimz22** [comment]
@rikkert  Ok, you say this is already possible, but can you provide information on how to do it?

**Comment by davedawson** [comment]
> Without or with a disabled input field this is already possible.

@rikkert Can you expand on that?

**Comment by rikkert** [comment]
I meant by using pikaday without an input field.
Or with an input field that is disabled for user input.

**Comment by davedawson** [comment]
Gotcha. Thanks, @rikkert. Adding `readonly="readonly"` to the text input seems to solve this problem. I don't see that in the docs anywhere, in case you want to update them.
