### ISSUE TITLE
parse and format function options

### ISSUE THREAD

**Issue by cyberbeat** [dbushell/Pikaday#441]
Sometimes moment.js is a too big (filesize) requirement. Much more simple and flexible would be to have 2 options:
formatFunc, parseFunc with sane defaults, for example

formatFunc: function(date){return date.toDateString();}
parseFunc: Date.parse

The moment-dependency then could be put to an extra module like the jquery extension. The default format and parse functions could simply be replaced by moment-calls

**Comment by rikkert** [comment]
Yes, thank you this is coming.
