### ISSUE TITLE
Using an overriding stylesheet to avoid frameworks to mess up layout

### ISSUE THREAD

**Issue by n4gashi** [dbushell/Pikaday#448]
I'm currently using Foundation in my current project. Tables are styled by Foundation and give me an unpleasant result. It would have been the case for any css line on table element or any element used for your Pikaday layout.

I would suggest to use !important wisely to avoid this issue.

**Comment by nathancahill** [comment]
No, including `!important` in a library to fix another library is not the way to go here. You'll have to include your own overrides, sorry.

**Comment by n4gashi** [comment]
Well, I do not share your opinion as it's used for your plugin to be consistent across all dev stacks (Foundation is a CSS framework as Bootstrap).
However, I do understand your position on that. I've already switched on another plugin anyway.

You can close this ticket as "won't fix" or whatever :+1: 
Thanks for answering :wink:
