### ISSUE TITLE
example amd

### ISSUE THREAD

**Issue by paulcayon** [dbushell/Pikaday#467]
this is just FYI, not critical ;)

when I execute /examples/amd.html, I have the following error : 
file://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.js Failed to load resource: net::ERR_FILE_NOT_FOUND

P.S: very good library :D

**Comment by rglyall** [comment]
That's because you're running off the file system rather than a web server. Change `<script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.js"></script>` to `<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.js"></script>` in `amd.html`.

**Comment by paulcayon** [comment]
ok, thanks
