### ISSUE TITLE
disableDayFn -Question

### ISSUE THREAD

**Issue by CraigDMcKenna** [dbushell/Pikaday#470]
Does anyone have an example of using `disableDayFn` with an asynchronous method call.  I have been trying this for some time now.  Here is my existing code using firebase.  It works great but only on the second render due to the async callback on `.child().child().on()`

```JavaScript
new Pikaday({ 
    field: document.getElementById('day'),
    disableWeekends: true,
    format: 'dddd, MMM Do, YYYY',
    minDate: today.toDate(),
    maxDate: max.toDate(),
    disableDayFn: function(theDate) {
      var day = Moment(theDate).format('YYYY-MM-DD') // same format as DB
      var notAvailable = false
          
      ref.child(day).child("available").on("value", function(availableSnapshot) {
          var availability = availableSnapshot.val()
            if (availability === 0) notAvailable = true
      })
      return notAvailable
    }
 })
```

Thanks!

**Comment by BMalaichik** [comment]
Hi, @craigdmckenna 
Did you find any better solution?
I also met this problem.
Thank you in advance!

**Comment by craigdmckenna** [comment]
@BMalaichik I was able to resolve this but I don't remember how. Later, perhaps this evening, I'll take a look at the code for you.

**Comment by BMalaichik** [comment]
@craigdmckenna thank you!

**Comment by craigdmckenna** [comment]
[here](https://github.com/craigdmckenna/vernal-hvac-site/tree/master/src/components/forms) is the completed form.

[here](http://craigdmckenna.github.io/vernal-hvac-site/#!/schedule-service) is the live version.

Let me know if you have any questions.

**Comment by BMalaichik** [comment]
@craigdmckenna thanks!

**Comment by tcheuD** [comment]
> [here](https://github.com/craigdmckenna/vernal-hvac-site/tree/master/src/components/forms) is the completed form.
> 
> [here](http://craigdmckenna.github.io/vernal-hvac-site/#!/schedule-service) is the live version.
> 
> Let me know if you have any questions.

Hi @craigdmckenna , both links are dead, 
I know it's been 4 years but do you still have an example of the solution by any chance ?

**Comment by tcheuD** [comment]
> > [here](https://github.com/craigdmckenna/vernal-hvac-site/tree/master/src/components/forms) is the completed form.
> > [here](http://craigdmckenna.github.io/vernal-hvac-site/#!/schedule-service) is the live version.
> > Let me know if you have any questions.
> 
> Hi @craigdmckenna , both links are dead,
> I know it's been 4 years but do you still have an example of the solution by any chance ?

Here is a solution I found yesterday (I didnt refactor the code yet, it's kinda messy but only the logic matter)
```javascript
        let available = [];
       
        var picker = new Pikaday({
            onDraw: function () {
                this.i = 0;
                available = [];
            },
            i: 0, //replace by a bool
            disableDayFn: function (t) {
                if (this.i === 0) {
                    this.i++
                    return getAvailableDates().then(() => {
                         return !available.includes(moment(t).format('YYYY-MM-DD'))
                    })
                } else {
                    return !available.includes(moment(t).format('YYYY-MM-DD'))
                }
            }
        });
```

**Comment by craigdmckenna** [comment]
```javascript
  export default {
    data () {
      return {
        appointments: {}
      }
    },
    props: ['id'],
    attached () {
      var self = this
      var updateAppointments = function(day) {
        var dayObject = self.$data.appointments
        dayObject[day.key()] = day.val()
        self.$data.appointments = dayObject
      }
      ref.on("child_added", updateAppointments)
      ref.on("child_changed", updateAppointments)
      ref.on("child_removed", updateAppointments)
      new Pikaday({
        field: document.getElementById(self.id),
        disableWeekends: true,
        format: 'dddd, MMM Do, YYYY',
        minDate: today.toDate(),
        maxDate: max.toDate(),
        disableDayFn: function(theDate) {
          var day = Moment(theDate).format('YYYY-MM-DD')
          return self.$data.appointments[day] && self.$data.appointments[day].available === 0
        }
      })
    }
  }
```
