### ISSUE TITLE
Add version number in JS / CSS files

### ISSUE THREAD

**Issue by alvarotrigo** [dbushell/Pikaday#489]
The JS and CSS files don't seem to contain a version number, which it is quite useful to see which version of the library is a project using. Otherwise we'll have to compare code accessing to the releases folder.

**Comment by alvarotrigo** [comment]
Sorry, I didn't realise it was included in the `component.json` file.

**Comment by sjmaceyful** [comment]
I think this should be reopened. If the component file isn't included in the project then there is no way to know what version is being used.
