### ISSUE TITLE
disableDayFn: not working

### ISSUE THREAD

**Issue by SLO-Robotics** [dbushell/Pikaday#500]
Hello,

I have tried several different ways to disable a day and none work... such as

disableDayFn: function('03/28/2016')

and

        disableDayFn: function('03/28/2016') {
           return disable = !disable;    
       }

and

 disableDayFn:  new Date('2016-03-03') ,

and a few others.. the only thing that makes it disable days is the example code of:
        disableDayFn: function(theDate) {
           return disable = !disable;    
       }

And that basicly just disables every other day (ohh joy.. of no use) 

Would be nice to know how to disable day(s).. like '03/07/2016,03/15/2016,03/27/2016' < 3 days disabled.

Ideas.. thoughts.. help?

Thanks
Shane

**Comment by rikkert** [comment]
You have to implement the function yourself and return wether the given date is selectable or not. (boolean)
