### ISSUE TITLE
Any option to select weeks?

### ISSUE THREAD

**Issue by Electrofenster** [dbushell/Pikaday#509]
Is there any solution to select a whole week like [this](http://jsfiddle.net/manishma/AVZJh/embedded/result/#Result)?

**Comment by Electrofenster** [comment]
After a few minutes I've got it:

```js
onSelect: function(date) {
    var first_ = (date.getDate() - date.getDay())+1;
    var last_ = first_ + 4;

    var firstday = new Date(date.setDate(first_));
    var lastday = new Date(date.setDate(last_));

    picker.setStartRange(firstday);
    picker.setEndRange(lastday);

    picker.draw();
}
```

**Comment by leizhao4** [comment]
@Electrofenster If you perfer having only one Pikaday instance instead of two, try my solution: https://github.com/leizhao4/Pikaday/tree/week-mode

**Comment by Electrofenster** [comment]
@leizhao4 Do you have any demo with it?

**Comment by leizhao4** [comment]
@Electrofenster I just added one. Check `examples/pick-whole-week.html`.
