### ISSUE TITLE
Remove Month / Year dropdown?

### ISSUE THREAD

**Issue by kkashou** [dbushell/Pikaday#543]
Is there a way to remove the functionality of year and month drop down on the date picker?

**Comment by gelus** [comment]
Do you mean so you are just stuck on one month? unable to switch?

I guess you could use CSS to hide the buttons you don't want your user to be able to use, and set the month manually in code.

**Comment by kkashou** [comment]
yeah I just went and display none the .pika-select selector ... thanks :)
