### ISSUE TITLE
no configuration: showDaysInNextAndPreviousMonths, when install from bower/npm

### ISSUE THREAD

**Issue by dmitrylebedev** [dbushell/Pikaday#554]
Hello, in pikaday.js, there is no method `showDaysInNextAndPreviousMonths` if I installed it by bower or npm

```json
  "dependencies": {
    "pikaday": "^1.4.0",
  }
```

**Comment by olihel** [comment]
This feature seems not to be published, yet. It was added after publishing 1.4.0 to the npm registry.

Waiting for this to be published!

**Comment by dmitrylebedev** [comment]
@olihel, ok, thank you

**Comment by eddie** [comment]
Any progress on this? Anything we can do to help?

**Comment by JossdEspinay** [comment]
hello, I also need this method. Is there any progress on this issue? Do you know when the next tag would be release? thanks

**Comment by rickydoar** [comment]
Any word on this being published?

**Comment by rikkert** [comment]
on it

**Comment by rikkert** [comment]
Use version 1.5.0
