### ISSUE TITLE
Date should be reset to null when user deletes the input content

### ISSUE THREAD

**Issue by cen1** [dbushell/Pikaday#575]
Not sure if this was discussed already, couldn't find it in the issue tracker.

1. Select a date
2. Call to getDate() returns correct date.
3. Delete the input content.
4. Call to getDate() returns the date from step 2.

Expected outcome: calling getDate() at step 4 should return null. 

I also noticed that Pikaday tends to return the last valid date if you type a wrong date into the input which is kinda unexpected behaviour. It should probably return null in that case too.

I made a workaround with an event listener on input field and setting date to null if value.length is zero but this should probably be handled by the library already.

**Comment by streamside** [comment]
Same problem described in #520

**Comment by cen1** [comment]
Missed it, closing.
