### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by inspo** [dbushell/Pikaday#583]
Hello. Init like
`var picker = new Pikaday({
    field: $('#datepicker')[0],
    firstDay: 1,
    format: 'YY-DD-MM'
});`
But it pastes in input like "Thu Sep 08 2016". Need "2016 08 09". Can you explain how to work with moment.js and this plug. Thanks.

**Comment by Waxi** [comment]
Make sure moment.js is loaded BEFORE pikaday.js otherwise it won't work.

**Comment by eikeco** [comment]
@inspo did that work?

**Comment by harimayco** [comment]
so we need to load another js file just for single date format like 'YYYY-DD-MM' ? really?
no thanks.

**Comment by rikkert** [comment]
For more advanced and flexible formatting you can pass your own toString function to the configuration which will be used to format the date object. This function has the following signature:

toString(date, format = 'YYYY-MM-DD')

You should return a string from it.

**Comment by brendanfalkowski** [comment]
FYI — here's a working snippet of the above. I needed the same thing but didn't want to add `moment.js` either:

```javascript
var datePickerFrom = new Pikaday({
    field: document.getElementById('date-from'),
    format: 'YYYY-MM-DD',
    toString: function (date, format) {
        var day   = date.getDate();
        var month = date.getMonth() + 1;
        var year  = date.getFullYear();

        var yyyy = year;
        var mm   = ((month > 9) ? '' : '0') + month;
        var dd   = ((day > 9)   ? '' : '0') + day;

        return yyyy + '-' + mm + '-' + dd;
    }
});
````
