### ISSUE TITLE
Calendar won't disappear after selecting a date

### ISSUE THREAD

**Issue by Dewayne0101** [dbushell/Pikaday#585]
I copied and pasted all of the code and implemented it on my web page and it all works except the calendar won't disappear after selecting the date. Anyone have any ideas?

**Comment by Dewayne0101** [comment]
I fixed it.

**Comment by bartonyoung** [comment]
Would you mind explaining what your fix was? I am using Pikadat with Mithril.js, and the calendar seems to try to "hide" but it is still visible on he screen.
