### ISSUE TITLE
Inactive repo?

### ISSUE THREAD

**Issue by kayazinc** [dbushell/Pikaday#587]
There are 102 pull requests, so is this repo inactive, ie. no longer maintain?

Please advise, thanks.

**Comment by espen** [comment]
Latest commit was in May so I wouldn't call that not maintained. However it's a very popular open source project so many people are asking questions and giving their input. Also keep in mind that this project aims to be a lightweight datepicker, not a do-everything datepicker.

**Comment by kayazinc** [comment]
Thanks for clarifying, @espen.
