### ISSUE TITLE
Duplicate months

### ISSUE THREAD

**Issue by jeantimex** [dbushell/Pikaday#597]
See this screenshot:

<img width="375" alt="screen shot 2016-10-25 at 1 27 37 pm" src="https://cloud.githubusercontent.com/assets/565300/19702973/d3250910-9ab6-11e6-8b08-b2240ca18d4d.png">

March and October appear twice! Sometimes it happens on Chrome, FF and IE11. Does anyone still maintaining this project? Thanks!

**Comment by rikkert** [comment]
Can you reproduce this with one of the examples?

**Comment by benjamin-richardson** [comment]
I just had a similar issue where I was giving my own function for the i18n when initialising PikaDay. Turns out my i18n function for getting month names had a error that only appears around the 30th and 31st of each month based on how I was generating a date.
