### ISSUE TITLE
1.5.0 render without field throwing error.

### ISSUE THREAD

**Issue by ming-codes** [dbushell/Pikaday#598]
This guy

<img width="594" alt="screen shot 2016-10-27 at 10 11 31 pm" src="https://cloud.githubusercontent.com/assets/706212/19795645/5f655650-9c92-11e6-9538-e86ef4094a08.png">

**Comment by ming-codes** [comment]
#567 related?

**Comment by rikkert** [comment]
Thanks, released 1.5.1.
