### ISSUE TITLE
[1.5.1] #setDate renders day before

### ISSUE THREAD

**Issue by ming-codes** [dbushell/Pikaday#599]
```js
var picker = new Pikaday();

picker.setDate('2016-10-28');
```

renders...

![screen shot 2016-10-28 at 9 24 56 am](https://cloud.githubusercontent.com/assets/706212/19813857/6ac025b2-9cf0-11e6-9b34-00bb23f3ecf2.png)

**Comment by ming-codes** [comment]
I think this is a browser issue around how Date.parse works.

**Comment by guzgarcia** [comment]
This bug still happen.

**Comment by diego77777** [comment]
bug still happen, even in firefox and chrome. Some workarounds? Any idea? Some way to add a day?

**Comment by terryroe** [comment]
As of today, this bug still exists.  I couldn't find another issue addressing this problem, so should this issue be reopened or a new issue created?
