### ISSUE TITLE
Option to disable keyboard support

### ISSUE THREAD

**Issue by IngoAlbers** [dbushell/Pikaday#607]
We have a setup where we require different inputs, for example mouse + external remote.
With the release of 1.5.1 using the external remote arrow keys now triggers the datepicker to change the date.
We need to avoid this. Is there any simple way to disable this behaviour at the moment?
If not would you be interested in a pull request that would add an option to enable and disable this functionality?

**Comment by NiallSmyth** [comment]
I'd be interested in that. I like the functionality, but I'm using pikaday as a permanently open calendar, so I want to be able to prevent the keyboard from changing the date when the user is focussed on e.g. a modal dialog. I'd welcome the PR, even if dbushell doesn't use it I'd merge it into my fork.

**Comment by IngoAlbers** [comment]
See: https://github.com/dbushell/Pikaday/pull/610

**Comment by liamwooding** [comment]
Being able to turn this off would be great for us too - we're using an always-open calendar embedded in a form, so some users are unwittingly changing dates while editing text fields.

**Comment by Scaalees** [comment]
Can we get a release for 1.7.0 please? Since this option is available in the docs, I got caught out by thinking it was available on the latest NPM version.

Thanks

**Comment by martinstender** [comment]
Maybe this is not the right place to make a bug report, but it is related, so:
Even though I have disabled some dates, I can still select them with keyboard arrow keys.
Is that fixed in 1.7.0 or will I have to disable keyboard input, when 1.7.0 is out?

Tia :-)

**Comment by rikkert** [comment]
Try with:
npm install dbushell/Pikaday

**Comment by martinstender** [comment]
Thank you, but that package doesn't seem to exist on npmjs.
We get many packages through npm, but none of them has a slash in the package identifier.
(I did try it however, but got an error).
