### ISSUE TITLE
Pressing enter or escape when no field is bound will cause an error

### ISSUE THREAD

**Issue by jsgoupil** [dbushell/Pikaday#611]
This code will cause the pikaday throw an error when no fields has been attached to the pikaday.

Cannot read property 'blur' of null

    switch(e.keyCode){
        case 13:
        case 27:
            opts.field.blur();
 
https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L489

**Comment by inzerceubytovani** [comment]
Same problem here

**Comment by josundt** [comment]
Same problem here. After upgrading to latest Pikaday release, lots of exceptions are logged in our application due to this. We had to revert to previous version. Should be a very easy fix, so I will create a pull request.

**Comment by barneycarroll** [comment]
You can work around this bug without adverse side-effects by supplying an input which is never injected into the document:

```javascript
new Pikaday({
  field : document.createElement('input'),
  ...opts
})
```

**Comment by barneycarroll** [comment]
You can get around this without any ostensible side-effects by chucking in an otherwise useless input after initialisation:

```javascript
var picker = new Pikaday(options);

picker._o.field = document.createElement('input');
```
