### ISSUE TITLE
Initialize only when `<input type="date">` isn't supported natively?

### ISSUE THREAD

**Issue by marcamos** [dbushell/Pikaday#616]
Is there anything in Pikaday to ensure it's not initialized in environments that natively support `<input type="date">`? Or, perhaps I should rely on something like Modernizr?

**Comment by yaykyle** [comment]
I don't see anything in Pikaday docs for that, but if you pull 'kr-register' I have Modernizr set up for that.

(I just in-lined Modernizr on this page for testing purposes. We can include it the normal way if you like).

**Comment by tttttony** [comment]
This is what I have, maybe it will work for your needs.

```
//Pikaday
var datefield = document.createElement("input");
datefield.setAttribute("type", "date");
if (datefield.type != "date") {
    //If browser doesn't have a native datepicker
    var datepickers = document.querySelectorAll('input[type="date"]');
    for (var i = 0; i < datepickers.length; i++) {
        new Pikaday({
            field: datepickers.item(i),
            firstDay: 1,
            minDate: new Date(2010, 1, 1),
            maxDate: new Date(2025, 12, 31),
            yearRange: [2000, 2035],
            format: 'MM/DD/YYYY'
        });
    }
}
```

**Comment by marcamos** [comment]
Thank you, @tttttony.

**Comment by C-Lodder** [comment]
Just an FYI, Safari recognises a native date input, however has not standard UI for it
