### ISSUE TITLE
prevent manual entry

### ISSUE THREAD

**Issue by El4a** [dbushell/Pikaday#622]
Since Ive problems with date parsing when I want to enter a data manually, I'll just opt for preventing the user to enter anything manually. Anyway I can do this with this lib? (Apart from just putting 'readonly' on the input)

**Comment by kylewetton** [comment]
I've personally opted for the readonly method, any reason why this doesn't work out for you?

**Comment by El4a** [comment]
There was a reason but now I can't think of it anymore. Maybe because readonly attribute is editable in the html, so susceptible to some intrusion? But all in all you're right, it's a good solution. and it doesn't matter anymore because I fixed the date parsing anyhow :) Thx for the reply!

**Comment by ShayanJa** [comment]
How did you guys make it readonly? i'm using it as an ember component
