### ISSUE TITLE
_onKeyChange memory leak

### ISSUE THREAD

**Issue by b8845** [dbushell/Pikaday#630]
Hi!

The _onKeyChange eventListener causes memory leak (see attached pic, between the two compared snapshot a Pikaday instance was created and destroyed).

You can solve this by adding the following line to the destroy function:
removeEvent(document, 'keydown', this._onKeyChange);
![kep](https://cloud.githubusercontent.com/assets/16955055/21719717/80fbe4d6-d41f-11e6-863c-24003a09effc.png)

**Comment by rodolfojnn** [comment]
I spent the last two hours investigating the source of this leak. You solved the problem, thank you!!!

**Comment by rikkert** [comment]
nice one, thanks!
