### ISSUE TITLE
Allow using custom formatting function

### ISSUE THREAD

**Issue by everdimension** [dbushell/Pikaday#653]
This feature would be especially handy if there's no moment.js available.
How about we could just pass a "formatter" (or "toString" function or whatever) which would be used here: https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L714-L717

The logic would be:
* if custom formatter is provided, use it and pass current date object to it
* if not, use moment `format`
* else use `.toDateString()`

The hardest thing would be to come up with the best name for this option :) I think both "formatter" and "toString" are good choices.

**Comment by everdimension** [comment]
I could create a PR if you would like to have this change.

**Comment by justrhysism** [comment]
Yeah the requirement for ALL of the rather large Moment.js library for formatting should be optional. If we could pass our own formatting functions, then we could use something like **date-fns** or even just roll our own.

**Comment by justrhysism** [comment]
> I could create a PR if you would like to have this change.

Make it intelligent so it defaults to current behaviour if a string is provided, I can't really see why it shouldn't be accepted.

**Comment by everdimension** [comment]
Created a PR: https://github.com/dbushell/Pikaday/pull/660

**Comment by rikkert** [comment]
Clossed with #660
