### ISSUE TITLE
Moment.js language setting

### ISSUE THREAD

**Issue by alican** [dbushell/Pikaday#67]
Setting of other languages with moment.js is easy, but Pikaday don't recognise the configuration. Is it possible to pass the moment.js language configuration to Pikadays i18n? The format is the same, for example:
https://github.com/timrwood/moment/blob/develop/min/langs.js

**Comment by elgubenis** [comment]
i would like to pass shortMonths to pikaday, but attaching it to the i18n does not do the trick, the shortmonths keep being in english

**Comment by dit-j** [comment]
@elgubenis  same issue...

**Comment by gonace** [comment]
was this ever solved, still getting the same issue ass @componentDidMount
