### ISSUE TITLE
Reverse order of years

### ISSUE THREAD

**Issue by frontendjim** [dbushell/Pikaday#671]
Hi there.

Awesome datepicker by the way!

I've themed the datepicker so month and year select lists are visible. Any way to reverse the order of the years so it's most recent first?

Many thanks

**Comment by willypt** [comment]
looking at the code, it's currently impossible. However, you can refer to `renderTitle` function and change it to your need

**Comment by frontendjim** [comment]
Ok great... thanks for the help.
