### ISSUE TITLE
Pikaday not working on mobile browsers

### ISSUE THREAD

**Issue by bramdevries** [dbushell/Pikaday#68]
I can't seem to get pikaday to work on a mobile browser( tested on chrome and safari for iOS). I did some testing and it seems the onSelect event never gets send out, thus the input field staying empty.

**Comment by mattferreira** [comment]
Was this issue resolved? Pikaday does not work for me on mobile devices. When I touch on a date on  mobile device(iphone5 & iphone 6) the calender disappears and the date I pick is not selected. I also can't move from month to month. When I press the arrows the pop-up disappears

**Comment by smkt** [comment]
I had a similar problem with Pikaday on mobile devices. I replaced 'ontouchend' with 'touchend' in addEvent call and now it works for me.

**Comment by dkirjakov** [comment]
The combination of both solutions changing "mousedown" in pikaday.js to "click" @aabutaleb  and "ontouchend" to "touchend" @smkt works out for me. Thanks.

**Comment by shahvikram24** [comment]
I tried to change the  events. but still not working.

 addEvent(self.el, 'touchend' in document ? 'touchend' : 'click', self._onClick, true);

**Comment by lehresman** [comment]
For those still having the issue, a combination of these solutions worked for me.  Here's the patch:
```
diff --git a/vendor/assets/javascripts/pikaday.js b/vendor/assets/javascripts/pikaday.js
index 9561a58..c419ab5 100644
--- a/vendor/assets/javascripts/pikaday.js
+++ b/vendor/assets/javascripts/pikaday.js
@@ -530,6 +530,7 @@
         self.el.className = 'pika-single' + (opts.isRTL ? ' is-rtl' : '');
 
         addEvent(self.el, 'mousedown', self._onMouseDown, true);
+        addEvent(self.el, 'touchend', self._onMouseDown, true);
         addEvent(self.el, 'change', self._onChange);
 
         if (opts.field) {
@@ -1011,6 +1012,7 @@
         {
             this.hide();
             removeEvent(this.el, 'mousedown', this._onMouseDown, true);
+            removeEvent(this.el, 'touchend', this._onMouseDown, true);
             removeEvent(this.el, 'change', this._onChange);
             if (this._o.field) {
                 removeEvent(this._o.field, 'change', this._onInputChange);
```

**Comment by rikkert** [comment]
thanks @lehresman, this is already the case in master.

**Comment by tariqalmalki** [comment]
> I can't seem to get pikaday to work on a mobile browser( tested on chrome and safari for iOS). I did some testing and it seems the onSelect event never gets send out, thus the input field staying empty.

i faced the same issue its working in computer but my mobile iphone its show when i put value in  alert "invalid ...."
i solved that by returning date in this format :
`toString(date, format) {
            var yyyy = date.getFullYear().toString();
           var mm = (date.getMonth()+1).toString(); // getMonth() is zero-based
           var dd  = date.getDate().toString();
           return yyyy + "-" + (mm[1]?mm:"0"+mm[0]) + "-" + (dd[1]?dd:"0"+dd[0]); // padding
        }`
