### ISSUE TITLE
Milligram css override pikaday style

### ISSUE THREAD

**Issue by rajasimon** [dbushell/Pikaday#681]
I'm developing application using Milligram css and I want datepicker. So far the style override by milligram css. Any idea how to get this work pikaday ?

![screenshot from 2017-05-10 15-41-47](https://cloud.githubusercontent.com/assets/6974101/25893884/4b511732-3597-11e7-9643-41e83a68493a.png)

**Comment by rajasimon** [comment]
Okay I included the pikaday css and it's working now. Please mention that in README. So new comers should check that.

**Comment by rikkert** [comment]
PR welcome
