### ISSUE TITLE
Add an extra day?

### ISSUE THREAD

**Issue by kkashou** [dbushell/Pikaday#701]
How do you add an extra day to the defaultDate option? I currently have new Date() but I would like to add plus one more day to that date.

I tried doing the following:

<pre>
defaultDate: moment().add({days: 1}).toDate();
</pre>

But it is not picking it up.

Thanks,

Kevin

**Comment by paouriel** [comment]
I managed to get it working, by trying this simple code.
`var picker = new Pikaday({
field: document.getElementById('yourid'), 
firstDay: 1,
format:'DD/MM/YYYY',
minDate: moment().toDate(),
maxDate: new Date(2100, 12, 31),
yearRange: [2016,2100],
minDate: moment().add({days: 0}).toDate()});`

Click here for [<script async src="//jsfiddle.net/eyceyu1q/embed/"></script>](Demo).

**Comment by paouriel** [comment]
I managed to solve this problem by this simple code fragment.

<pre>
var picker = new Pikaday({
  field: document.getElementById('yourid'),
  firstDay: 1,
  format: 'DD/MM/YYYY',
  minDate: moment().toDate(), //set current date
  maxDate: new Date(2100, 12, 31),
  yearRange: [2016, 2100],
  minDate: moment().add({
    days: 0
  }).toDate()
});
</pre>

Try it <a href="//jsfiddle.net/eyceyu1q/embed/">here.</a>

**Comment by paouriel** [comment]
I managed to solve this problem by this simple code fragment.

<pre>
var picker = new Pikaday({
  field: document.getElementById('yourid'),
  firstDay: 1,
  format: 'DD/MM/YYYY',
  minDate: moment().toDate(), //set current date
  maxDate: new Date(2100, 12, 31),
  yearRange: [2016, 2100],
  minDate: moment().add({days: 0}).toDate()
});
</pre>

JSFiddle? Try it <a href="//jsfiddle.net/eyceyu1q/embed/">here.</a>
