### ISSUE TITLE
Always Visible datepicker

### ISSUE THREAD

**Issue by pankajpatel** [dbushell/Pikaday#706]
Can this datepicker be always visible on some container element and I handle the show hide of that element separately.

In other words, we should not strictly need an input to have a datepicker. 

Can it be done?

**Comment by hectorlorenzo** [comment]
Yes, you can find an example in `/examples/container.html`. Just set the option `bound` to `false`, and set the `container` option to any element you want the datepicker to be displayed in. You can use the API to control the display separately.
