### ISSUE TITLE
Remove the moment.js optional dependency

### ISSUE THREAD

**Issue by NindroidX** [dbushell/Pikaday#718]
Moment.js is not really optional at the moment. If you use npm install, moment will still be installed. You could use the '--no-optional' flag, but that only works the first time you install Pikaday.

This means that if you use Webpack to include Pikaday, moment.js will also be included automatically..

Why not just remove the dependency from the package.json file, and let the user decide if moment.js is needed?

**Comment by rikkert** [comment]
This is what optional dependencies are meant for right.
Why is webpack picking it up? It should only do that if you have referenced moment in your code already somewhere else.

**Comment by NindroidX** [comment]
I guess because pikaday tries to `require('moment');`.

npm still tries to install packages in the optionalDependencies list so if you install pikaday with `npm install pikaday,` moment.js also gets installed, and because of the require it will also get bundled if you use Webpack.

I would just remove moment from the optionalDependencies list. If someone wants to use moment.js with Pikaday, they can npm install it themselves. This is what I thought was already the case when I read "No dependencies (but plays well with Moment.js)" in the Readme.

**Comment by rikkert** [comment]
It still needs to be loaded by Pikaday to use it.
For now please use:
```javascript
plugins: [
  new webpack.IgnorePlugin(/moment/)
]
````

**Comment by NindroidX** [comment]
It will still be loaded, even if it's removed from the optionalDependencies, if the user of the library also adds moment to his own dependency list. This has the main benefit that users who don't want to use moment.js don't need to change their build tool configs. And Webpack users don't get unexpectedly large bundle sizes.

In any case, I would at least add a note to the readme, telling that moment.js is automatically loaded if you use Webpack.

**Comment by rikkert** [comment]
Are you saying if it is removed from optionalDependencies all is well?
If you can make a PR for this with README additions that would be great!

**Comment by NindroidX** [comment]
Yes, I think it will be fine then. `Npm install pikaday --save` will no longer try to install moment.js, and because moment is no longer in the node_modules folder, webpack won't be able to find and bundle it either.

And users who do want moment.js can just install it themselves.

I will test it to be sure, and create a PR if I find some time.
