### ISSUE TITLE
How I can config language?

### ISSUE THREAD

**Issue by huangche007** [dbushell/Pikaday#729]
I am a Chinese，so i wanna config language be Chinese,but i do not know how?

**Comment by huangche007** [comment]
Yeah I solved the problem

**Comment by iCok** [comment]
@huangche007 how did you do that?

**Comment by iCok** [comment]
Oh, I figured out, here is an example for russian language:

`  var ruDate = {
                            previousMonth : 'Предыдущий месяц',
                            nextMonth     : 'Следующий месяц',
                            months        : ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
                            weekdays      : ['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'],
                            weekdaysShort : ['Вс','Пн','Вт','Ср','Чт','Пт','Сб']
                        };
                        var picker = new Pikaday({
                            field: document.getElementById('initial-date'),
                            i18n: ruDate,
                            firstDay: 1
                        });`

**Comment by iCok** [comment]
@rikkert please close the issue
