### ISSUE TITLE
KeyboardInput option not used in package from npm

### ISSUE THREAD

**Issue by silverspectro** [dbushell/Pikaday#732]
Hello,
I think there is a problem with the keyboardInput option in the package on NPM.
I checked the code pulled from `npm install pikaday` and it seems that the option isn't used and the event is constantly added.

it seems that the latest commits are not in the release and the code comes from this commit : https://github.com/dbushell/Pikaday/blob/2216628502e986368362af7420f9afee9cc30d1c/pikaday.js

Could it be possible to just cherry-pick the commit that adds the option ? because it is quite troublesome actually, every keydown on the page makes the calendar update his date.

**Comment by rikkert** [comment]
Done
